Repository OCA/account-analytic, pull requests merged in 2020-12, with the labels that each got.

#343 [14.0][MIG] mrp_analytic
  mrp_analytic/README.rst
  mrp_analytic/__init__.py
  mrp_analytic/__manifest__.py
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/de.po
  mrp_analytic/i18n/el_GR.po
  mrp_analytic/i18n/es.po
  mrp_analytic/i18n/es_MX.po
  mrp_analytic/i18n/fi.po
  mrp_analytic/i18n/fr.po
  mrp_analytic/i18n/hr.po
  mrp_analytic/i18n/mrp_analytic.pot
  mrp_analytic/i18n/pt_BR.po
  mrp_analytic/i18n/sk_SK.po
  mrp_analytic/i18n/sl.po
  mrp_analytic/i18n/tr.po
  mrp_analytic/i18n/zh_CN.po
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/mrp_production.py
  mrp_analytic/readme/CONTRIBUTORS.rst
  mrp_analytic/readme/DESCRIPTION.rst
  mrp_analytic/readme/HISTORY.rst
  mrp_analytic/readme/USAGE.rst
  mrp_analytic/static/description/icon.png
  mrp_analytic/static/description/icon.svg
  mrp_analytic/static/description/index.html
  mrp_analytic/tests/__init__.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
  setup/mrp_analytic/odoo/addons/mrp_analytic
  setup/mrp_analytic/setup.py
Labels: bot is merging ⏳

#315 [11.0][ADD] account_analytic_asset
  account_analytic_asset/README.rst
  account_analytic_asset/__init__.py
  account_analytic_asset/__manifest__.py
  account_analytic_asset/models/__init__.py
  account_analytic_asset/models/analytic_account_asset.py
  account_analytic_asset/readme/CONTRIBUTORS.rst
  account_analytic_asset/readme/DESCRIPTION.rst
  account_analytic_asset/static/description/icon.png
  account_analytic_asset/static/description/index.html
  account_analytic_asset/tests/__init__.py
  account_analytic_asset/tests/test_asset_analytic_account.py
  account_analytic_asset/views/account_asset_asset.xml
Labels: approved, bot is merging ⏳, ready to merge

#312 [13.0][mig] analytic_tag_dimension_sale_warning
  analytic_tag_dimension_sale_warning/README.rst
  analytic_tag_dimension_sale_warning/__init__.py
  analytic_tag_dimension_sale_warning/__manifest__.py
  analytic_tag_dimension_sale_warning/i18n/ca.po
  analytic_tag_dimension_sale_warning/i18n/de.po
  analytic_tag_dimension_sale_warning/i18n/es.po
  analytic_tag_dimension_sale_warning/i18n/es_CO.po
  analytic_tag_dimension_sale_warning/i18n/fr.po
  analytic_tag_dimension_sale_warning/models/__init__.py
  analytic_tag_dimension_sale_warning/models/analytic.py
  analytic_tag_dimension_sale_warning/models/sale.py
  analytic_tag_dimension_sale_warning/readme/CONTRIBUTORS.rst
  analytic_tag_dimension_sale_warning/readme/DESCRIPTION.rst
  analytic_tag_dimension_sale_warning/readme/HISTORY.rst
  analytic_tag_dimension_sale_warning/readme/INSTALL.rst
  analytic_tag_dimension_sale_warning/static/description/icon.png
  analytic_tag_dimension_sale_warning/static/description/index.html
  setup/analytic_tag_dimension_sale_warning/odoo/addons/analytic_tag_dimension_sale_warning
  setup/analytic_tag_dimension_sale_warning/setup.py
Labels: approved, bot is merging ⏳
