Repository OCA/account-analytic, pull requests merged in 2020-03, with the labels that each got.

#286 [12.0][FIX] stock_analytic apply AA on COGS account in customer invoice
  stock_analytic/models/__init__.py
  stock_analytic/models/product_product.py
Labels: approved, ready to merge

#265 [12.0][MIG] account_move_analytic_recreate
  account_move_analytic_recreate/README.rst
  account_move_analytic_recreate/__init__.py
  account_move_analytic_recreate/__manifest__.py
  account_move_analytic_recreate/i18n/account_move_analytic_recreate.pot
  account_move_analytic_recreate/models/__init__.py
  account_move_analytic_recreate/models/account_move.py
  account_move_analytic_recreate/readme/CONTRIBUTORS.rst
  account_move_analytic_recreate/readme/DESCRIPTION.rst
  account_move_analytic_recreate/static/description/icon.png
Labels: approved, ready to merge

#296 [12.0][IMP] account_analytic_parent: filter using account or child accounts
  account_analytic_parent/__manifest__.py
  account_analytic_parent/views/account_analytic_line.xml
Labels: approved

#288 [12.0][FIX] stock_analytic: moves with different analytic accounts
  stock_analytic/models/stock.py
Labels: approved, ready to merge

#276 [13.0][MIG] procurement_mto_analytic
  procurement_mto_analytic/README.rst
  procurement_mto_analytic/__init__.py
  procurement_mto_analytic/__manifest__.py
  procurement_mto_analytic/i18n/procurement_mto_analytic.pot
  procurement_mto_analytic/i18n/purchase_procurement_analytic.pot
  procurement_mto_analytic/models/__init__.py
  procurement_mto_analytic/models/sale_order_line.py
  procurement_mto_analytic/models/stock_move.py
  procurement_mto_analytic/models/stock_rule.py
  procurement_mto_analytic/readme/CONTRIBUTORS.rst
  procurement_mto_analytic/readme/DESCRIPTION.rst
  procurement_mto_analytic/readme/HISTORY.rst
  procurement_mto_analytic/readme/USAGE.rst
  procurement_mto_analytic/static/description/icon.png
  procurement_mto_analytic/static/description/index.html
  procurement_mto_analytic/tests/__init__.py
  procurement_mto_analytic/tests/test_purchase_procurement_analytic.py
  setup/procurement_mto_analytic/odoo/addons/procurement_mto_analytic
  setup/procurement_mto_analytic/setup.py
Labels: approved, ready to merge

#268 13.0 mig account analytic parent
  account_analytic_parent/README.rst
  account_analytic_parent/__init__.py
  account_analytic_parent/__manifest__.py
  account_analytic_parent/data/analytic_account_demo.xml
  account_analytic_parent/hooks.py
  account_analytic_parent/i18n/account_analytic_parent.pot
  account_analytic_parent/i18n/ca.po
  account_analytic_parent/i18n/cs_CZ.po
  account_analytic_parent/i18n/de.po
  account_analytic_parent/i18n/el_GR.po
  account_analytic_parent/i18n/es.po
  account_analytic_parent/i18n/es_EC.po
  account_analytic_parent/i18n/es_MX.po
  account_analytic_parent/i18n/fi.po
  account_analytic_parent/i18n/fr.po
  account_analytic_parent/i18n/gl.po
  account_analytic_parent/i18n/gl_ES.po
  account_analytic_parent/i18n/gu_IN.po
  account_analytic_parent/i18n/hi_IN.po
  account_analytic_parent/i18n/hr.po
  account_analytic_parent/i18n/hr_HR.po
  account_analytic_parent/i18n/nl.po
  account_analytic_parent/i18n/nl_NL.po
  account_analytic_parent/i18n/pt_BR.po
  account_analytic_parent/i18n/ru.po
  account_analytic_parent/i18n/sk_SK.po
  account_analytic_parent/i18n/sl.po
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_parent/models/__init__.py
  account_analytic_parent/models/account_analytic_account.py
  account_analytic_parent/readme/CONTRIBUTORS.rst
  account_analytic_parent/readme/DESCRIPTION.rst
  account_analytic_parent/readme/USAGE.rst
  account_analytic_parent/static/description/icon.png
  account_analytic_parent/static/description/index.html
  account_analytic_parent/tests/__init__.py
  account_analytic_parent/tests/test_account_analytic_account.py
  account_analytic_parent/views/account_analytic_account_view.xml
  setup/account_analytic_parent/odoo/addons/account_analytic_parent
  setup/account_analytic_parent/setup.py
Labels: approved, ready to merge

#297 [12.0][IMP] account_analytic_sequence: assign on install
  account_analytic_parent/tests/test_account_analytic_account.py
  account_analytic_sequence/__init__.py
  account_analytic_sequence/__manifest__.py
  account_analytic_sequence/hooks.py
  account_analytic_sequence/models/__init__.py
  account_analytic_sequence/models/account_analytic_account.py
  account_analytic_sequence/readme/CONTRIBUTORS.rst
  account_analytic_sequence/tests/__init__.py
  account_analytic_sequence/tests/test_analytic_sequence.py
Labels: approved, ready to merge

#278 [13.0][MIG] purchase_analytic
  purchase_analytic/README.rst
  purchase_analytic/__init__.py
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/__init__.py
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/readme/DESCRIPTION.rst
  purchase_analytic/readme/HISTORY.rst
  purchase_analytic/static/description/icon.png
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/__init__.py
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
  setup/purchase_analytic/odoo/addons/purchase_analytic
  setup/purchase_analytic/setup.py
Labels: approved, bot is merging ⏳, ready to merge
