Repository OCA/account-analytic, pull requests merged in 2020-05, with the labels that each got.

#303 [12.0][IMP] analytic_tag_dimension: Sync dimension code and description changes
  analytic_tag_dimension/README.rst
  analytic_tag_dimension/__manifest__.py
  analytic_tag_dimension/models/analytic.py
  analytic_tag_dimension/readme/CONTRIBUTORS.rst
  analytic_tag_dimension/static/description/index.html
  analytic_tag_dimension/tests/test_analytic_dimension.py
Labels: approved, bot is merging ⏳

#298 13.0 mig stock analytic
  setup/stock_analytic/odoo/addons/stock_analytic
  setup/stock_analytic/setup.py
  stock_analytic/README.rst
  stock_analytic/__init__.py
  stock_analytic/__manifest__.py
  stock_analytic/i18n/ca.po
  stock_analytic/i18n/cs_CZ.po
  stock_analytic/i18n/de.po
  stock_analytic/i18n/el_GR.po
  stock_analytic/i18n/es.po
  stock_analytic/i18n/es_EC.po
  stock_analytic/i18n/es_MX.po
  stock_analytic/i18n/fi.po
  stock_analytic/i18n/fr.po
  stock_analytic/i18n/gl.po
  stock_analytic/i18n/gu_IN.po
  stock_analytic/i18n/hi_IN.po
  stock_analytic/i18n/hr.po
  stock_analytic/i18n/hr_HR.po
  stock_analytic/i18n/hu.po
  stock_analytic/i18n/it.po
  stock_analytic/i18n/nl.po
  stock_analytic/i18n/pt.po
  stock_analytic/i18n/pt_BR.po
  stock_analytic/i18n/pt_PT.po
  stock_analytic/i18n/ro.po
  stock_analytic/i18n/sk_SK.po
  stock_analytic/i18n/sl.po
  stock_analytic/i18n/stock_analytic.pot
  stock_analytic/i18n/tr.po
  stock_analytic/i18n/tr_TR.po
  stock_analytic/i18n/vi_VN.po
  stock_analytic/i18n/zh_CN.po
  stock_analytic/models/__init__.py
  stock_analytic/models/product_product.py
  stock_analytic/models/stock.py
  stock_analytic/models/stock_scrap.py
  stock_analytic/static/description/icon.png
  stock_analytic/tests/__init__.py
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/tests/test_stock_scrap.py
  stock_analytic/views/stock_move_views.xml
  stock_analytic/views/stock_scrap.xml
Labels: approved, bot is merging ⏳, ready to merge

#275 [13.0][MIG] mrp_analytic
  mrp_analytic/README.rst
  mrp_analytic/__init__.py
  mrp_analytic/__manifest__.py
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/de.po
  mrp_analytic/i18n/el_GR.po
  mrp_analytic/i18n/es.po
  mrp_analytic/i18n/es_MX.po
  mrp_analytic/i18n/fi.po
  mrp_analytic/i18n/fr.po
  mrp_analytic/i18n/hr.po
  mrp_analytic/i18n/mrp_analytic.pot
  mrp_analytic/i18n/pt_BR.po
  mrp_analytic/i18n/sk_SK.po
  mrp_analytic/i18n/sl.po
  mrp_analytic/i18n/tr.po
  mrp_analytic/i18n/zh_CN.po
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/mrp_production.py
  mrp_analytic/readme/CONTRIBUTORS.rst
  mrp_analytic/readme/DESCRIPTION.rst
  mrp_analytic/readme/HISTORY.rst
  mrp_analytic/readme/USAGE.rst
  mrp_analytic/static/description/icon.png
  mrp_analytic/static/description/icon.svg
  mrp_analytic/static/description/index.html
  mrp_analytic/tests/__init__.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
  setup/mrp_analytic/odoo/addons/mrp_analytic
  setup/mrp_analytic/setup.py
Labels: bot is merging ⏳
