Repository OCA/account-analytic, pull requests merged in 2020-07, with the labels that each got.

#310 [13.0][MIG] analytic_tag_dimension
  analytic_tag_dimension/README.rst
  analytic_tag_dimension/__init__.py
  analytic_tag_dimension/__manifest__.py
  analytic_tag_dimension/demo/analytic_demo.xml
  analytic_tag_dimension/i18n/analytic_tag_dimension.pot
  analytic_tag_dimension/i18n/ar.po
  analytic_tag_dimension/i18n/bs.po
  analytic_tag_dimension/i18n/ca.po
  analytic_tag_dimension/i18n/cs.po
  analytic_tag_dimension/i18n/cs_CZ.po
  analytic_tag_dimension/i18n/de.po
  analytic_tag_dimension/i18n/en_GB.po
  analytic_tag_dimension/i18n/es.po
  analytic_tag_dimension/i18n/es_CO.po
  analytic_tag_dimension/i18n/es_CR.po
  analytic_tag_dimension/i18n/es_EC.po
  analytic_tag_dimension/i18n/es_MX.po
  analytic_tag_dimension/i18n/et.po
  analytic_tag_dimension/i18n/fi.po
  analytic_tag_dimension/i18n/fr.po
  analytic_tag_dimension/i18n/fr_CH.po
  analytic_tag_dimension/i18n/hr.po
  analytic_tag_dimension/i18n/hr_HR.po
  analytic_tag_dimension/i18n/hu.po
  analytic_tag_dimension/i18n/it.po
  analytic_tag_dimension/i18n/ja.po
  analytic_tag_dimension/i18n/lt.po
  analytic_tag_dimension/i18n/mk.po
  analytic_tag_dimension/i18n/mn.po
  analytic_tag_dimension/i18n/nb.po
  analytic_tag_dimension/i18n/nl.po
  analytic_tag_dimension/i18n/nl_BE.po
  analytic_tag_dimension/i18n/nl_NL.po
  analytic_tag_dimension/i18n/pt.po
  analytic_tag_dimension/i18n/pt_BR.po
  analytic_tag_dimension/i18n/pt_PT.po
  analytic_tag_dimension/i18n/ro.po
  analytic_tag_dimension/i18n/ru.po
  analytic_tag_dimension/i18n/sl.po
  analytic_tag_dimension/i18n/sv.po
  analytic_tag_dimension/i18n/tr.po
  analytic_tag_dimension/i18n/tr_TR.po
  analytic_tag_dimension/i18n/zh_CN.po
  analytic_tag_dimension/i18n/zh_TW.po
  analytic_tag_dimension/models/__init__.py
  analytic_tag_dimension/models/account_invoice_report.py
  analytic_tag_dimension/models/analytic.py
  analytic_tag_dimension/readme/CONFIGURE.rst
  analytic_tag_dimension/readme/CONTRIBUTORS.rst
  analytic_tag_dimension/readme/CREDITS.rst
  analytic_tag_dimension/readme/DESCRIPTION.rst
  analytic_tag_dimension/readme/ROADMAP.rst
  analytic_tag_dimension/security/ir.model.access.csv
  analytic_tag_dimension/static/description/icon.png
  analytic_tag_dimension/static/description/index.html
  analytic_tag_dimension/tests/__init__.py
  analytic_tag_dimension/tests/test_analytic_dimension.py
  analytic_tag_dimension/views/analytic_view.xml
  setup/analytic_tag_dimension/odoo/addons/analytic_tag_dimension
  setup/analytic_tag_dimension/setup.py
Labels: bot is merging ⏳

#292 [12.0][account_analytic_required] company_dependent analytic_policy
  account_analytic_distribution_required/models/account.py
  account_analytic_distribution_required/tests/test_account_analytic_plan_required.py
  account_analytic_required/__manifest__.py
  account_analytic_required/migrations/12.0.2.0.0/post-migrate.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account.xml
Labels: approved, bot is merging ⏳

#246 [12.0][MIG]analytic_tag_dimension_purchase_warning
  analytic_tag_dimension_purchase_warning/README.rst
  analytic_tag_dimension_purchase_warning/__init__.py
  analytic_tag_dimension_purchase_warning/__manifest__.py
  analytic_tag_dimension_purchase_warning/i18n/analytic_tag_dimension_purchase_warning.pot
  analytic_tag_dimension_purchase_warning/i18n/ca.po
  analytic_tag_dimension_purchase_warning/i18n/de.po
  analytic_tag_dimension_purchase_warning/i18n/es.po
  analytic_tag_dimension_purchase_warning/i18n/es_CO.po
  analytic_tag_dimension_purchase_warning/i18n/fr.po
  analytic_tag_dimension_purchase_warning/models/__init__.py
  analytic_tag_dimension_purchase_warning/models/purchase.py
  analytic_tag_dimension_purchase_warning/readme/CONFIGURE.rst
  analytic_tag_dimension_purchase_warning/readme/CONTRIBUTORS.rst
  analytic_tag_dimension_purchase_warning/readme/DESCRIPTION.rst
  analytic_tag_dimension_purchase_warning/static/description/icon.png
Labels: approved, bot is merging ⏳, ready to merge

#272 [13.0][MIG] analytic_base_department
  analytic_base_department/README.rst
  analytic_base_department/__init__.py
  analytic_base_department/__manifest__.py
  analytic_base_department/i18n/analytic_base_department.pot
  analytic_base_department/i18n/ca.po
  analytic_base_department/i18n/de.po
  analytic_base_department/i18n/el_GR.po
  analytic_base_department/i18n/es.po
  analytic_base_department/i18n/es_CO.po
  analytic_base_department/i18n/es_MX.po
  analytic_base_department/i18n/fi.po
  analytic_base_department/i18n/fr.po
  analytic_base_department/i18n/gu_IN.po
  analytic_base_department/i18n/hi_IN.po
  analytic_base_department/i18n/hr_HR.po
  analytic_base_department/i18n/nl.po
  analytic_base_department/i18n/pt.po
  analytic_base_department/i18n/pt_BR.po
  analytic_base_department/i18n/sk_SK.po
  analytic_base_department/i18n/sl.po
  analytic_base_department/i18n/zh_CN.po
  analytic_base_department/models/__init__.py
  analytic_base_department/models/analytic.py
  analytic_base_department/readme/CONTRIBUTORS.rst
  analytic_base_department/readme/DESCRIPTION.rst
  analytic_base_department/readme/HISTORY.rst
  analytic_base_department/static/description/icon.png
  analytic_base_department/static/description/index.html
  analytic_base_department/tests/__init__.py
  analytic_base_department/tests/test_line_department.py
  analytic_base_department/views/analytic.xml
  setup/analytic_base_department/odoo/addons/analytic_base_department
  setup/analytic_base_department/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#263 [12.0][ADD] account_analytic_line_name_text
  account_analytic_line_name_text/README.rst
  account_analytic_line_name_text/__init__.py
  account_analytic_line_name_text/__manifest__.py
  account_analytic_line_name_text/models/__init__.py
  account_analytic_line_name_text/models/account_analytic_line.py
  account_analytic_line_name_text/readme/CONTRIBUTORS.rst
  account_analytic_line_name_text/readme/DESCRIPTION.rst
  account_analytic_line_name_text/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#293 [13.0][account_analytic_required] company_dependent analytic_policy
  account_analytic_required/__manifest__.py
  account_analytic_required/migrations/13.0.2.0.0/post-migrate.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account.xml
Labels: approved, bot is merging ⏳, ready to merge

#308 [12.0][FIX] analytic_tag_dimension: avoid column not exists
  analytic_tag_dimension/models/account_invoice_report.py
  analytic_tag_dimension/models/analytic.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#311 [12.0][FIX+IMP]: analytic_partner_hr_timesheet: Proper partner smart-button
  analytic_partner_hr_timesheet/models/res_partner.py
  analytic_partner_hr_timesheet/tests/test_analytic_partner_hr_timesheet.py
  analytic_partner_hr_timesheet/views/res_partner_views.xml
Labels: bot is merging ⏳
