Repository OCA/account-analytic, pull requests merged in 2021-05, with the labels that each got.

#364 [13.0] analytic_base_department: fixed and improved search views
  analytic_base_department/__manifest__.py
  analytic_base_department/readme/CONTRIBUTORS.rst
  analytic_base_department/views/analytic.xml
Labels: approved, bot is merging ⏳, ready to merge

#358 [13.0][ADD] account_analytic_tag_default
  account_analytic_tag_default/README.rst
  account_analytic_tag_default/__init__.py
  account_analytic_tag_default/__manifest__.py
  account_analytic_tag_default/models/__init__.py
  account_analytic_tag_default/models/account_analytic_account.py
  account_analytic_tag_default/models/account_move.py
  account_analytic_tag_default/readme/CONFIGURE.rst
  account_analytic_tag_default/readme/CONTRIBUTORS.rst
  account_analytic_tag_default/readme/DESCRIPTION.rst
  account_analytic_tag_default/readme/USAGE.rst
  account_analytic_tag_default/static/description/icon.png
  account_analytic_tag_default/static/description/index.html
  account_analytic_tag_default/tests/__init__.py
  account_analytic_tag_default/tests/test_account_analytic_tag_default.py
  account_analytic_tag_default/views/account_analytic_account_view.xml
  setup/account_analytic_tag_default/odoo/addons/account_analytic_tag_default
  setup/account_analytic_tag_default/setup.py
Labels: approved, bot is merging ⏳

#377 [13.0][IMP] stock_analytic: Prevent error when set real_time valuation and stock.valuation.layer is auto-created
  stock_analytic/tests/test_stock_picking.py
Labels: bot is merging ⏳

#359 [14.0] [NEW] mrp_analytic_sale_project: New module added in the repo.
  mrp_analytic_sale_project/README.rst
  mrp_analytic_sale_project/__init__.py
  mrp_analytic_sale_project/__manifest__.py
  mrp_analytic_sale_project/models/__init__.py
  mrp_analytic_sale_project/models/sale_order.py
  mrp_analytic_sale_project/readme/CONTRIBUTORS.rst
  mrp_analytic_sale_project/readme/DESCRIPTION.rst
  mrp_analytic_sale_project/readme/USAGE.rst
  mrp_analytic_sale_project/tests/__init__.py
  mrp_analytic_sale_project/tests/test_sale_analytic.py
  setup/mrp_analytic_sale_project/odoo/addons/mrp_analytic_sale_project
  setup/mrp_analytic_sale_project/setup.py
Labels: bot is merging ⏳

#361 [14.0] [NEW] mrp_analytic_child_mo: New module added in the repo.
  mrp_analytic_child_mo/README.rst
  mrp_analytic_child_mo/__init__.py
  mrp_analytic_child_mo/__manifest__.py
  mrp_analytic_child_mo/models/__init__.py
  mrp_analytic_child_mo/models/mrp_production.py
  mrp_analytic_child_mo/readme/CONTRIBUTORS.rst
  mrp_analytic_child_mo/readme/DESCRIPTION.rst
  mrp_analytic_child_mo/tests/__init__.py
  mrp_analytic_child_mo/tests/test_mrp_analytic.py
  setup/mrp_analytic_child_mo/odoo/addons/mrp_analytic_child_mo
  setup/mrp_analytic_child_mo/setup.py
Labels: bot is merging ⏳

#318 [13.0][MIG] analytic_tag_dimension_enhanced
  analytic_tag_dimension_enhanced/README.rst
  analytic_tag_dimension_enhanced/__init__.py
  analytic_tag_dimension_enhanced/__manifest__.py
  analytic_tag_dimension_enhanced/i18n/analytic_tag_dimension_enhanced.pot
  analytic_tag_dimension_enhanced/models/__init__.py
  analytic_tag_dimension_enhanced/models/account_analytic_dimension.py
  analytic_tag_dimension_enhanced/models/account_analytic_tag.py
  analytic_tag_dimension_enhanced/models/analytic_dimension_line.py
  analytic_tag_dimension_enhanced/readme/CONFIGURE.rst
  analytic_tag_dimension_enhanced/readme/CONTRIBUTORS.rst
  analytic_tag_dimension_enhanced/readme/DESCRIPTION.rst
  analytic_tag_dimension_enhanced/static/description/icon.png
  analytic_tag_dimension_enhanced/static/description/index.html
  analytic_tag_dimension_enhanced/tests/__init__.py
  analytic_tag_dimension_enhanced/tests/test_analytic_dimension.py
  analytic_tag_dimension_enhanced/views/account_move_view.xml
  analytic_tag_dimension_enhanced/views/analytic_view.xml
  setup/analytic_tag_dimension_enhanced/odoo/addons/analytic_tag_dimension_enhanced
  setup/analytic_tag_dimension_enhanced/setup.py
Labels: approved, bot is merging ⏳, ready to merge
