Repository OCA/account-analytic, pull requests merged in 2021-02, with the labels that each got.

#351 [IMP] analytic_activity_based_cost: add parent/child relation , improve create/write logic
  analytic_activity_based_cost/__manifest__.py
  analytic_activity_based_cost/models/__init__.py
  analytic_activity_based_cost/models/activity_cost_rule.py
  analytic_activity_based_cost/models/analytic_account.py
  analytic_activity_based_cost/models/product_template.py
  analytic_activity_based_cost/readme/CONFIGURATION.rst
  analytic_activity_based_cost/views/activity_cost_rule_views.xml
  analytic_activity_based_cost/views/analytic_account_line.xml
  analytic_activity_based_cost/views/product_template.xml
Labels: bot is merging ⏳

#350 [FIX] pos_analytic_by_config tests
  pos_analytic_by_config/tests/test_pos_analytic_by_config.py
Labels: approved, bot is merging ⏳, ready to merge

#363 14.0 mig account analytic parent
  account_analytic_parent/README.rst
  account_analytic_parent/__init__.py
  account_analytic_parent/__manifest__.py
  account_analytic_parent/data/analytic_account_demo.xml
  account_analytic_parent/hooks.py
  account_analytic_parent/i18n/ab.po
  account_analytic_parent/i18n/account_analytic_parent.pot
  account_analytic_parent/i18n/ca.po
  account_analytic_parent/i18n/cs_CZ.po
  account_analytic_parent/i18n/de.po
  account_analytic_parent/i18n/el_GR.po
  account_analytic_parent/i18n/es.po
  account_analytic_parent/i18n/es_EC.po
  account_analytic_parent/i18n/es_MX.po
  account_analytic_parent/i18n/fi.po
  account_analytic_parent/i18n/fr.po
  account_analytic_parent/i18n/gl.po
  account_analytic_parent/i18n/gl_ES.po
  account_analytic_parent/i18n/gu_IN.po
  account_analytic_parent/i18n/hi_IN.po
  account_analytic_parent/i18n/hr.po
  account_analytic_parent/i18n/hr_HR.po
  account_analytic_parent/i18n/nl.po
  account_analytic_parent/i18n/nl_NL.po
  account_analytic_parent/i18n/pt_BR.po
  account_analytic_parent/i18n/ru.po
  account_analytic_parent/i18n/sk_SK.po
  account_analytic_parent/i18n/sl.po
  account_analytic_parent/i18n/th.po
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_parent/models/__init__.py
  account_analytic_parent/models/account_analytic_account.py
  account_analytic_parent/readme/CONTRIBUTORS.rst
  account_analytic_parent/readme/DESCRIPTION.rst
  account_analytic_parent/readme/USAGE.rst
  account_analytic_parent/static/description/icon.png
  account_analytic_parent/static/description/index.html
  account_analytic_parent/tests/__init__.py
  account_analytic_parent/tests/test_account_analytic_account.py
  account_analytic_parent/views/account_analytic_account_view.xml
  setup/account_analytic_parent/odoo/addons/account_analytic_parent
  setup/account_analytic_parent/setup.py
Labels: approved, bot is merging ⏳
