Repository OCA/account-analytic, pull requests merged in 2022-08, with the labels that each got.

#352 [13.0][ADD] procurement_mto_analytic - only add account_analytic_id in po domain if value is there
  procurement_mto_analytic/models/stock_rule.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#436 [15.0][MIG] account_analytic_required
  account_analytic_required/README.rst
  account_analytic_required/__init__.py
  account_analytic_required/__manifest__.py
  account_analytic_required/i18n/account_analytic_required.pot
  account_analytic_required/i18n/ar.po
  account_analytic_required/i18n/ca.po
  account_analytic_required/i18n/de.po
  account_analytic_required/i18n/es.po
  account_analytic_required/i18n/es_CO.po
  account_analytic_required/i18n/fr.po
  account_analytic_required/i18n/hr_HR.po
  account_analytic_required/i18n/nl.po
  account_analytic_required/i18n/pt_BR.po
  account_analytic_required/i18n/sv.po
  account_analytic_required/i18n/zh_CN.po
  account_analytic_required/models/__init__.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONFIGURE.rst
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/readme/DESCRIPTION.rst
  account_analytic_required/readme/USAGE.rst
  account_analytic_required/static/description/icon.png
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/__init__.py
  account_analytic_required/tests/test_account_analytic_required.py
  account_analytic_required/views/account_account_type.xml
  setup/account_analytic_required/odoo/addons/account_analytic_required
  setup/account_analytic_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#333 [13.0][ADD] new module purchase_stock_analytic
  purchase_stock_analytic/README.rst
  purchase_stock_analytic/__init__.py
  purchase_stock_analytic/__manifest__.py
  purchase_stock_analytic/models/__init__.py
  purchase_stock_analytic/models/purchase_order_line.py
  purchase_stock_analytic/static/description/icon.png
  purchase_stock_analytic/tests/__init__.py
  purchase_stock_analytic/tests/test_purchase_stock_analytic.py
  setup/purchase_stock_analytic/.eggs/README.txt
  setup/purchase_stock_analytic/odoo/addons/purchase_stock_analytic
  setup/purchase_stock_analytic/setup.py
Labels: approved, bot is merging ⏳

#473 [13.0][IMP] purchase_analytic: adapt to newest framework.
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: approved, bot is merging ⏳

#478 [15.0][IMP] purchase_analytic: adapt to newest framework.
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: bot is merging ⏳

#477 [14.0][IMP] purchase_analytic: adapt to newest framework.
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
Labels: bot is merging ⏳

#450 15.0 mig mrp analytic
  mrp_analytic/README.rst
  mrp_analytic/__init__.py
  mrp_analytic/__manifest__.py
  mrp_analytic/i18n/ca.po
  mrp_analytic/i18n/de.po
  mrp_analytic/i18n/el_GR.po
  mrp_analytic/i18n/es.po
  mrp_analytic/i18n/es_MX.po
  mrp_analytic/i18n/fi.po
  mrp_analytic/i18n/fr.po
  mrp_analytic/i18n/hr.po
  mrp_analytic/i18n/mrp_analytic.pot
  mrp_analytic/i18n/pt_BR.po
  mrp_analytic/i18n/sk_SK.po
  mrp_analytic/i18n/sl.po
  mrp_analytic/i18n/tr.po
  mrp_analytic/i18n/zh_CN.po
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/mrp_production.py
  mrp_analytic/models/stock_move.py
  mrp_analytic/readme/CONTRIBUTORS.rst
  mrp_analytic/readme/DESCRIPTION.rst
  mrp_analytic/readme/HISTORY.rst
  mrp_analytic/readme/USAGE.rst
  mrp_analytic/static/description/icon.png
  mrp_analytic/static/description/icon.svg
  mrp_analytic/static/description/index.html
  mrp_analytic/tests/__init__.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
  setup/mrp_analytic/odoo/addons/mrp_analytic
  setup/mrp_analytic/setup.py
Labels: bot is merging ⏳, stale

#389 [14.0][FIX] analytic_tag_dimension_enhanced: not check required dimension in non-invoice
  analytic_tag_dimension_enhanced/models/account_analytic_tag.py
  analytic_tag_dimension_enhanced/tests/test_analytic_dimension.py
Labels: needs review, bot is merging ⏳, stale

#334 [13.0][ADD] new module sale_stock_analytic
  sale_stock_analytic/README.rst
  sale_stock_analytic/__init__.py
  sale_stock_analytic/__manifest__.py
  sale_stock_analytic/models/__init__.py
  sale_stock_analytic/models/stock_rule.py
  sale_stock_analytic/static/description/icon.png
  sale_stock_analytic/tests/__init__.py
  sale_stock_analytic/tests/test_sale_stock_analytic.py
  setup/sale_stock_analytic/.eggs/README.txt
  setup/sale_stock_analytic/odoo/addons/sale_stock_analytic
  setup/sale_stock_analytic/setup.py
Labels: bot is merging ⏳, stale

#408 [FIX] analytic_activity_based_cost: rounding issue
  analytic_activity_based_cost/models/product.py
Labels: bot is merging ⏳

#479 [14.0][FIX] account_analytic_wip: Analytic Account was not carried to WIP Journal Items
  account_analytic_wip/models/account_analytic_tracking.py
Labels: approved, bot is merging ⏳

#461 [15.0][MIG] analytic_base_department: Migration to 15.0
  analytic_base_department/README.rst
  analytic_base_department/__init__.py
  analytic_base_department/__manifest__.py
  analytic_base_department/i18n/analytic_base_department.pot
  analytic_base_department/i18n/ca.po
  analytic_base_department/i18n/de.po
  analytic_base_department/i18n/el_GR.po
  analytic_base_department/i18n/es.po
  analytic_base_department/i18n/es_CO.po
  analytic_base_department/i18n/es_MX.po
  analytic_base_department/i18n/fi.po
  analytic_base_department/i18n/fr.po
  analytic_base_department/i18n/gu_IN.po
  analytic_base_department/i18n/hi_IN.po
  analytic_base_department/i18n/hr_HR.po
  analytic_base_department/i18n/nl.po
  analytic_base_department/i18n/pt.po
  analytic_base_department/i18n/pt_BR.po
  analytic_base_department/i18n/sk_SK.po
  analytic_base_department/i18n/sl.po
  analytic_base_department/i18n/zh_CN.po
  analytic_base_department/models/__init__.py
  analytic_base_department/models/analytic.py
  analytic_base_department/models/hr_department.py
  analytic_base_department/readme/CONTRIBUTORS.rst
  analytic_base_department/readme/DESCRIPTION.rst
  analytic_base_department/readme/HISTORY.rst
  analytic_base_department/static/description/icon.png
  analytic_base_department/static/description/index.html
  analytic_base_department/tests/__init__.py
  analytic_base_department/tests/test_line_department.py
  analytic_base_department/views/analytic.xml
  analytic_base_department/views/hr_department_views.xml
  setup/analytic_base_department/odoo/addons/analytic_base_department
  setup/analytic_base_department/setup.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳
