Repository OCA/account-analytic, pull requests merged in 2022-05, with the labels that each got.

#454 [IMP] Update template - Switch to github actions
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
Labels: bot is merging ⏳

#376 [14.0][MIG] product_analytic_purchase: Migration to 14.0
  product_analytic_purchase/README.rst
  product_analytic_purchase/__init__.py
  product_analytic_purchase/__manifest__.py
  product_analytic_purchase/i18n/ca.po
  product_analytic_purchase/i18n/cs_CZ.po
  product_analytic_purchase/i18n/es.po
  product_analytic_purchase/i18n/fr.po
  product_analytic_purchase/i18n/hr.po
  product_analytic_purchase/i18n/product_analytic_purchase.pot
  product_analytic_purchase/models/__init__.py
  product_analytic_purchase/models/purchase_order_line.py
  product_analytic_purchase/static/description/icon.png
  product_analytic_purchase/tests/__init__.py
  product_analytic_purchase/tests/test_purchase.py
  setup/product_analytic_purchase/odoo/addons/product_analytic_purchase
  setup/product_analytic_purchase/setup.py
Labels: approved, bot is merging ⏳

#412 [14.0][IMP] stock_analytic: Transmit analytic account to new moves
  stock_analytic/models/stock.py
Labels: bot is merging ⏳

#403 [REF][IMP][FIX] account_analytic_wip: use actuals to post WIP, dont post variances until Close
  account_analytic_wip/__manifest__.py
  account_analytic_wip/data/ir_config_parameter_data.xml
  account_analytic_wip/demo/product_demo.xml
  account_analytic_wip/models/__init__.py
  account_analytic_wip/models/account_analytic_line.py
  account_analytic_wip/models/account_analytic_tracking.py
  account_analytic_wip/models/account_move.py
  account_analytic_wip/models/product_category.py
  account_analytic_wip/models/product_template.py
  account_analytic_wip/tests/test_analytic.py
  account_analytic_wip/views/account_analytic_tracking.xml
  account_analytic_wip/views/product_category.xml
  account_analytic_wip/views/product_category_view.xml
  analytic_activity_based_cost/models/account_analytic_line.py
Labels: bot is merging ⏳

#456 [14.0][MIG] purchase_request_analytic
  purchase_request_analytic/README.rst
  purchase_request_analytic/__init__.py
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/i18n/purchase_request_analytic.pot
  purchase_request_analytic/models/__init__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/readme/CONTRIBUTORS.rst
  purchase_request_analytic/readme/DESCRIPTION.rst
  purchase_request_analytic/readme/HISTORY.rst
  purchase_request_analytic/readme/USAGE.rst
  purchase_request_analytic/static/description/icon.png
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/__init__.py
  purchase_request_analytic/tests/test_purchase_request_analytic.py
  purchase_request_analytic/views/purchase_request_views.xml
  setup/purchase_request_analytic/odoo/addons/purchase_request_analytic
  setup/purchase_request_analytic/setup.py
Labels: approved, bot is merging ⏳

#426 [14.0][FIX] analytic_tag_dimension_enhanced: domain_tag follow line_ids (journal items)
  analytic_tag_dimension_enhanced/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#458 [14.0][FIX] account_analytic_wip: fix cron error
  account_analytic_wip/models/account_analytic_tracking.py
Labels: approved, bot is merging ⏳
