Repository OCA/account-analytic, pull requests merged in 2023-10, with the labels that each got.

#594 [MIG] product_analytic: Migration to 16.0
  product_analytic/README.rst
  product_analytic/__init__.py
  product_analytic/__manifest__.py
  product_analytic/demo/product_demo.xml
  product_analytic/i18n/ar.po
  product_analytic/i18n/bs.po
  product_analytic/i18n/ca.po
  product_analytic/i18n/cs.po
  product_analytic/i18n/cs_CZ.po
  product_analytic/i18n/de.po
  product_analytic/i18n/en_GB.po
  product_analytic/i18n/es.po
  product_analytic/i18n/es_CO.po
  product_analytic/i18n/es_CR.po
  product_analytic/i18n/es_EC.po
  product_analytic/i18n/es_MX.po
  product_analytic/i18n/et.po
  product_analytic/i18n/fi.po
  product_analytic/i18n/fr.po
  product_analytic/i18n/fr_CH.po
  product_analytic/i18n/hr.po
  product_analytic/i18n/hr_HR.po
  product_analytic/i18n/hu.po
  product_analytic/i18n/it.po
  product_analytic/i18n/ja.po
  product_analytic/i18n/lt.po
  product_analytic/i18n/mk.po
  product_analytic/i18n/mn.po
  product_analytic/i18n/nb.po
  product_analytic/i18n/nl.po
  product_analytic/i18n/nl_BE.po
  product_analytic/i18n/nl_NL.po
  product_analytic/i18n/product_analytic.pot
  product_analytic/i18n/pt.po
  product_analytic/i18n/pt_BR.po
  product_analytic/i18n/pt_PT.po
  product_analytic/i18n/ro.po
  product_analytic/i18n/ru.po
  product_analytic/i18n/sl.po
  product_analytic/i18n/sv.po
  product_analytic/i18n/tr.po
  product_analytic/i18n/tr_TR.po
  product_analytic/i18n/zh_CN.po
  product_analytic/i18n/zh_TW.po
  product_analytic/models/__init__.py
  product_analytic/models/account_move.py
  product_analytic/models/product.py
  product_analytic/models/product_category.py
  product_analytic/readme/CONTRIBUTORS.rst
  product_analytic/readme/DESCRIPTION.rst
  product_analytic/readme/HISTORY.rst
  product_analytic/readme/USAGE.rst
  product_analytic/static/description/icon.png
  product_analytic/static/description/index.html
  product_analytic/tests/__init__.py
  product_analytic/tests/test_account_move.py
  product_analytic/views/product_view.xml
  setup/product_analytic/odoo/addons/product_analytic
  setup/product_analytic/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#571 [15.0][FWP] product_analytic
  product_analytic/models/account_move.py
Labels: approved, bot is merging ⏳

#598 [13.0][IMP] purchase_analytic: avoid overwrite context in views inherited
  purchase_analytic/__manifest__.py
  purchase_analytic/views/purchase_views.xml
Labels: approved, bot is merging ⏳

#599 [14.0][IMP] purchase_analytic: avoid override context in views inherited
  purchase_analytic/__manifest__.py
  purchase_analytic/views/purchase_views.xml
Labels: bot is merging ⏳

#600 [15.0][IMP] purchase_analytic: avoid overwrite context in views inherited
  purchase_analytic/__manifest__.py
  purchase_analytic/views/purchase_views.xml
Labels: bot is merging ⏳

#603 [16.0][ADD] hr_expense_analytic_tag: New module
  hr_expense_analytic_tag/README.rst
  hr_expense_analytic_tag/__init__.py
  hr_expense_analytic_tag/__manifest__.py
  hr_expense_analytic_tag/i18n/es.po
  hr_expense_analytic_tag/i18n/hr_expense_analytic_tag.pot
  hr_expense_analytic_tag/models/__init__.py
  hr_expense_analytic_tag/models/hr_expense.py
  hr_expense_analytic_tag/readme/CONTRIBUTORS.rst
  hr_expense_analytic_tag/readme/DESCRIPTION.rst
  hr_expense_analytic_tag/static/description/icon.png
  hr_expense_analytic_tag/static/description/index.html
  hr_expense_analytic_tag/tests/__init__.py
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
  hr_expense_analytic_tag/views/hr_expense_view.xml
  setup/hr_expense_analytic_tag/odoo/addons/hr_expense_analytic_tag
  setup/hr_expense_analytic_tag/setup.py
Labels: bot is merging ⏳

#604 [16.0][ADD] sale_analytic_tag: New module
  sale_analytic_tag/README.rst
  sale_analytic_tag/__init__.py
  sale_analytic_tag/__manifest__.py
  sale_analytic_tag/i18n/es.po
  sale_analytic_tag/i18n/sale_analytic_tag.pot
  sale_analytic_tag/models/__init__.py
  sale_analytic_tag/models/sale_order_line.py
  sale_analytic_tag/readme/CONTRIBUTORS.rst
  sale_analytic_tag/readme/DESCRIPTION.rst
  sale_analytic_tag/static/description/icon.png
  sale_analytic_tag/static/description/index.html
  sale_analytic_tag/tests/__init__.py
  sale_analytic_tag/tests/test_sale_analytic_tag.py
  sale_analytic_tag/views/sale_order_view.xml
  setup/sale_analytic_tag/odoo/addons/sale_analytic_tag
  setup/sale_analytic_tag/setup.py
Labels: approved, bot is merging ⏳
