Repository OCA/account-analytic, pull requests merged in 2023-07, with the labels that each got.

#570 [13.0][FIX]product_analytic: ensure move type in dict
  product_analytic/models/account_move.py
Labels: bot is merging ⏳

#485 [14.0][ADD] stock_warehouse_analytic
  setup/stock_warehouse_analytic/odoo/addons/stock_warehouse_analytic
  setup/stock_warehouse_analytic/setup.py
  stock_warehouse_analytic/README.rst
  stock_warehouse_analytic/__init__.py
  stock_warehouse_analytic/__manifest__.py
  stock_warehouse_analytic/models/__init__.py
  stock_warehouse_analytic/models/stock_warehouse.py
  stock_warehouse_analytic/readme/CONTRIBUTORS.rst
  stock_warehouse_analytic/readme/DESCRIPTION.rst
  stock_warehouse_analytic/static/description/icon.png
  stock_warehouse_analytic/static/description/index.html
  stock_warehouse_analytic/views/stock_warehouse.xml
Labels: approved, bot is merging ⏳

#568 [15.0][MIG] partner_analytic
  partner_analytic/README.rst
  partner_analytic/__init__.py
  partner_analytic/__manifest__.py
  partner_analytic/i18n/partner_analytic.pot
  partner_analytic/models/__init__.py
  partner_analytic/models/account_move.py
  partner_analytic/models/res_partner.py
  partner_analytic/readme/CONTRIBUTORS.rst
  partner_analytic/readme/DESCRIPTION.rst
  partner_analytic/readme/USAGE.rst
  partner_analytic/static/description/icon.png
  partner_analytic/static/description/index.html
  partner_analytic/tests/__init__.py
  partner_analytic/tests/test_partner_analytic.py
  partner_analytic/views/partner_views.xml
  setup/partner_analytic/odoo/addons/partner_analytic
  setup/partner_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#577 [14.0][IMP] stock_analytic: add analytic account to move tree receipt picki…
  stock_analytic/views/stock_move_views.xml
Labels: approved, bot is merging ⏳

#578 [15.0][IMP] stock_analytic: add analytic account to move tree receipt…
  stock_analytic/views/stock_move_views.xml
Labels: needs review, approved, bot is merging ⏳

#539 [15.0][mig]-purchase_request_analytic
  purchase_request_analytic/README.rst
  purchase_request_analytic/__init__.py
  purchase_request_analytic/__manifest__.py
  purchase_request_analytic/i18n/purchase_request_analytic.pot
  purchase_request_analytic/models/__init__.py
  purchase_request_analytic/models/purchase_request.py
  purchase_request_analytic/readme/CONTRIBUTORS.rst
  purchase_request_analytic/readme/DESCRIPTION.rst
  purchase_request_analytic/readme/HISTORY.rst
  purchase_request_analytic/readme/USAGE.rst
  purchase_request_analytic/static/description/icon.png
  purchase_request_analytic/static/description/index.html
  purchase_request_analytic/tests/__init__.py
  purchase_request_analytic/tests/test_purchase_request_analytic.py
  purchase_request_analytic/views/purchase_request_views.xml
  setup/purchase_request_analytic/odoo/addons/purchase_request_analytic
  setup/purchase_request_analytic/setup.py
Labels: approved, bot is merging ⏳
