Repository OCA/account-analytic, pull requests merged in 2023-08, with the labels that each got.

#527 [16.0][MIG] stock_picking_analytic: Migration to 16.0
  setup/stock_picking_analytic/odoo/addons/stock_picking_analytic
  setup/stock_picking_analytic/setup.py
  stock_picking_analytic/README.rst
  stock_picking_analytic/__init__.py
  stock_picking_analytic/__manifest__.py
  stock_picking_analytic/i18n/stock_picking_analytic.pot
  stock_picking_analytic/models/__init__.py
  stock_picking_analytic/models/stock_picking.py
  stock_picking_analytic/readme/CONTRIBUTORS.rst
  stock_picking_analytic/readme/DESCRIPTION.rst
  stock_picking_analytic/static/description/icon.png
  stock_picking_analytic/static/description/index.html
  stock_picking_analytic/tests/__init__.py
  stock_picking_analytic/tests/test_picking_analytic_account.py
  stock_picking_analytic/views/stock_picking.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#583 [16.0][IMP] stock_analytic: add analytic distribution to move tree re…
  stock_analytic/views/stock_move_views.xml
Labels: approved

#422 [14.0][MIG] account_analytic_no_lines
  account_analytic_no_lines/README.rst
  account_analytic_no_lines/__init__.py
  account_analytic_no_lines/__manifest__.py
  account_analytic_no_lines/i18n/account_analytic_no_lines.pot
  account_analytic_no_lines/i18n/ca.po
  account_analytic_no_lines/i18n/cs_CZ.po
  account_analytic_no_lines/i18n/de.po
  account_analytic_no_lines/i18n/el_GR.po
  account_analytic_no_lines/i18n/es.po
  account_analytic_no_lines/i18n/es_EC.po
  account_analytic_no_lines/i18n/es_MX.po
  account_analytic_no_lines/i18n/fi.po
  account_analytic_no_lines/i18n/fr.po
  account_analytic_no_lines/i18n/gu_IN.po
  account_analytic_no_lines/i18n/hi_IN.po
  account_analytic_no_lines/i18n/hr.po
  account_analytic_no_lines/i18n/hr_HR.po
  account_analytic_no_lines/i18n/nl.po
  account_analytic_no_lines/i18n/nl_NL.po
  account_analytic_no_lines/i18n/pt.po
  account_analytic_no_lines/i18n/pt_BR.po
  account_analytic_no_lines/i18n/ru.po
  account_analytic_no_lines/i18n/sk_SK.po
  account_analytic_no_lines/i18n/sl.po
  account_analytic_no_lines/i18n/zh_CN.po
  account_analytic_no_lines/models/__init__.py
  account_analytic_no_lines/models/account_analytic_account.py
  account_analytic_no_lines/models/account_move_line.py
  account_analytic_no_lines/readme/CONTRIBUTORS.rst
  account_analytic_no_lines/readme/DESCRIPTION.rst
  account_analytic_no_lines/security/data_account_analytic_group.xml
  account_analytic_no_lines/static/description/icon.png
  account_analytic_no_lines/tests/__init__.py
  account_analytic_no_lines/tests/test_account_analytic_no_lines.py
  account_analytic_no_lines/views/account_analytic.xml
  account_analytic_no_lines/views/account_analytic_account.xml
  account_analytic_no_lines/views/account_move_line.xml
  setup/account_analytic_no_lines/odoo/addons/account_analytic_no_lines
  setup/account_analytic_no_lines/setup.py
Labels: needs review, approved, bot is merging ⏳

#572 [16.0][ADD] account_analytic_tag
  account_analytic_tag/README.rst
  account_analytic_tag/__init__.py
  account_analytic_tag/__manifest__.py
  account_analytic_tag/i18n/account_analytic_tag.pot
  account_analytic_tag/i18n/en_US.po
  account_analytic_tag/i18n/es.po
  account_analytic_tag/models/__init__.py
  account_analytic_tag/models/account_analytic_line.py
  account_analytic_tag/models/account_analytic_tag.py
  account_analytic_tag/models/account_move_line.py
  account_analytic_tag/models/res_config_settings.py
  account_analytic_tag/readme/CONFIGURE.rst
  account_analytic_tag/readme/CONTRIBUTORS.rst
  account_analytic_tag/readme/DESCRIPTION.rst
  account_analytic_tag/readme/USAGE.rst
  account_analytic_tag/security/analytic_security.xml
  account_analytic_tag/security/ir.model.access.csv
  account_analytic_tag/static/description/icon.png
  account_analytic_tag/static/description/index.html
  account_analytic_tag/tests/__init__.py
  account_analytic_tag/tests/common.py
  account_analytic_tag/tests/test_account_analytic_tag.py
  account_analytic_tag/views/account_analytic_line_views.xml
  account_analytic_tag/views/account_analytic_tag_views.xml
  account_analytic_tag/views/account_move_views.xml
  account_analytic_tag/views/res_config_settings_views.xml
  setup/account_analytic_tag/odoo/addons/account_analytic_tag
  setup/account_analytic_tag/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
