Repository OCA/account-analytic, pull requests merged in 2023-02, with the labels that each got.

#535 [16.0][FIX] Update copier template
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: approved

#524 [MIG] purchase_analytic: Migration to 16.0
  purchase_analytic/README.rst
  purchase_analytic/__init__.py
  purchase_analytic/__manifest__.py
  purchase_analytic/i18n/es.po
  purchase_analytic/i18n/fr.po
  purchase_analytic/i18n/purchase_analytic.pot
  purchase_analytic/models/__init__.py
  purchase_analytic/models/purchase.py
  purchase_analytic/readme/CONTRIBUTORS.rst
  purchase_analytic/readme/DESCRIPTION.rst
  purchase_analytic/readme/HISTORY.rst
  purchase_analytic/static/description/icon.png
  purchase_analytic/static/description/index.html
  purchase_analytic/tests/__init__.py
  purchase_analytic/tests/test_purchase_analytic.py
  purchase_analytic/views/purchase_views.xml
  setup/purchase_analytic/odoo/addons/purchase_analytic
  setup/purchase_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#528 [16.0][IMP] stock_analytic: add validation on analytic distribution
  stock_analytic/README.rst
  stock_analytic/__manifest__.py
  stock_analytic/models/__init__.py
  stock_analytic/models/analytic_applicability.py
  stock_analytic/models/stock_move.py
  stock_analytic/models/stock_picking.py
  stock_analytic/models/stock_scrap.py
  stock_analytic/readme/CONFIGURE.rst
  stock_analytic/readme/CONTRIBUTORS.rst
  stock_analytic/readme/DESCRIPTION.rst
  stock_analytic/readme/USAGE.rst
  stock_analytic/static/description/index.html
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/tests/test_stock_scrap.py
  stock_analytic/views/stock_move_line_views.xml
  stock_analytic/views/stock_scrap_views.xml
Labels: approved, bot is merging ⏳

#532 [15.0][IMP] account_move_update_analytic: hide button column when not posted
  account_move_update_analytic/views/account_move_view.xml
  account_move_update_analytic/wizards/account_move_update_analytic.py
Labels: approved, bot is merging ⏳
