Repository OCA/account-analytic, pull requests merged in 2023-11, with the labels that each got.

#605 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_analytic_wip/i18n/account_analytic_wip.pot
  account_analytic_wip/views/account_analytic_tracking.xml
  analytic_activity_based_cost/views/product.xml
  analytic_tag_dimension/i18n/analytic_tag_dimension.pot
  analytic_tag_dimension/views/analytic_view.xml
  stock_analytic/views/stock_move_views.xml
  stock_inventory_analytic/views/res_config_settings_views.xml
Labels: needs review, bot is merging ⏳

#579 [15.0][FIX] mrp_analytic: remove duplicate field
  mrp_analytic/__manifest__.py
  mrp_analytic/models/__init__.py
  mrp_analytic/models/analytic_account.py
  mrp_analytic/models/mrp_production.py
  mrp_analytic/models/stock_move.py
  mrp_analytic/tests/test_mrp_analytic.py
  mrp_analytic/views/analytic_account_view.xml
  mrp_analytic/views/mrp_view.xml
Labels: approved, bot is merging ⏳

#582 [15.0][FIX] pos_analytic_by_config: update signature of _get_sale_vals
  pos_analytic_by_config/models/pos_session.py
Labels: approved, bot is merging ⏳

#585 [16.0][ADD] account_analytic_account_tag
  account_analytic_account_tag/README.rst
  account_analytic_account_tag/__init__.py
  account_analytic_account_tag/__manifest__.py
  account_analytic_account_tag/i18n/account_analytic_account_tag.pot
  account_analytic_account_tag/i18n/fr.po
  account_analytic_account_tag/models/__init__.py
  account_analytic_account_tag/models/account_analytic_account.py
  account_analytic_account_tag/readme/CONTRIBUTORS.rst
  account_analytic_account_tag/readme/DESCRIPTION.rst
  account_analytic_account_tag/static/description/index.html
  account_analytic_account_tag/views/account_analytic_account_views.xml
  setup/account_analytic_account_tag/odoo/addons/account_analytic_account_tag
  setup/account_analytic_account_tag/setup.py
Labels: needs review, approved, bot is merging ⏳
