Repository OCA/account-analytic, pull requests merged in 2023-09, with the labels that each got.

#546 [15.0][FIX] analytic_tag_dimension: test script savepointcase to transactioncase
  analytic_tag_dimension/tests/test_analytic_dimension.py
Labels: bot is merging ⏳, stale

#587 [16.0][ADD] account_analytic_tag_distribution: New module
  account_analytic_tag/tests/common.py
  account_analytic_tag_distribution/README.rst
  account_analytic_tag_distribution/__init__.py
  account_analytic_tag_distribution/__manifest__.py
  account_analytic_tag_distribution/i18n/account_analytic_tag_distribution.pot
  account_analytic_tag_distribution/i18n/es.po
  account_analytic_tag_distribution/models/__init__.py
  account_analytic_tag_distribution/models/account_analytic_tag.py
  account_analytic_tag_distribution/models/account_move_line.py
  account_analytic_tag_distribution/readme/CONTRIBUTORS.rst
  account_analytic_tag_distribution/readme/DESCRIPTION.rst
  account_analytic_tag_distribution/readme/USAGE.rst
  account_analytic_tag_distribution/static/description/icon.png
  account_analytic_tag_distribution/static/description/index.html
  account_analytic_tag_distribution/tests/__init__.py
  account_analytic_tag_distribution/tests/test_account_analytic_tag_distribution.py
  account_analytic_tag_distribution/views/account_analytic_tag_views.xml
  account_analytic_tag_distribution/views/account_move_views.xml
  setup/account_analytic_tag_distribution/odoo/addons/account_analytic_tag_distribution
  setup/account_analytic_tag_distribution/setup.py
Labels: approved, bot is merging ⏳

#559 [16.0][MIG] account_move_update_analytic
  account_move_update_analytic/README.rst
  account_move_update_analytic/__init__.py
  account_move_update_analytic/__manifest__.py
  account_move_update_analytic/i18n/account_move_update_analytic.pot
  account_move_update_analytic/i18n/fr.po
  account_move_update_analytic/models/__init__.py
  account_move_update_analytic/readme/CONTRIBUTORS.rst
  account_move_update_analytic/readme/DESCRIPTION.rst
  account_move_update_analytic/readme/USAGE.rst
  account_move_update_analytic/security/ir.model.access.csv
  account_move_update_analytic/static/description/icon.png
  account_move_update_analytic/static/description/index.html
  account_move_update_analytic/static/description/update_from_invoice.png
  account_move_update_analytic/static/description/update_from_journals.png
  account_move_update_analytic/views/account_move_line_view.xml
  account_move_update_analytic/views/account_move_view.xml
  account_move_update_analytic/wizards/__init__.py
  account_move_update_analytic/wizards/account_move_update_analytic.py
  account_move_update_analytic/wizards/account_move_update_analytic_view.xml
  setup/account_move_update_analytic/odoo/addons/account_move_update_analytic
  setup/account_move_update_analytic/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#592 [16.0][FIX] purchase_analytic: Access Denied by ACLs
  purchase_analytic/views/purchase_views.xml
Labels: approved, bot is merging ⏳

#593 [15.0][FIX] account_move_update_analytic: Switch button text to icon
  account_move_update_analytic/__manifest__.py
  account_move_update_analytic/i18n/account_move_update_analytic.pot
  account_move_update_analytic/i18n/es.po
  account_move_update_analytic/views/account_move_line_view.xml
  account_move_update_analytic/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳
