Repository OCA/account-analytic, pull requests merged in 2024-05, with the labels that each got.

#638 [17.0] [MIG] account_analytic_tag: Migration to 17.0
  account_analytic_tag/README.rst
  account_analytic_tag/__init__.py
  account_analytic_tag/__manifest__.py
  account_analytic_tag/i18n/account_analytic_tag.pot
  account_analytic_tag/i18n/ca.po
  account_analytic_tag/i18n/en_US.po
  account_analytic_tag/i18n/es.po
  account_analytic_tag/i18n/it.po
  account_analytic_tag/i18n/pt_BR.po
  account_analytic_tag/models/__init__.py
  account_analytic_tag/models/account_analytic_line.py
  account_analytic_tag/models/account_analytic_tag.py
  account_analytic_tag/models/account_move_line.py
  account_analytic_tag/models/res_config_settings.py
  account_analytic_tag/pyproject.toml
  account_analytic_tag/readme/CONFIGURE.md
  account_analytic_tag/readme/CONTRIBUTORS.md
  account_analytic_tag/readme/DESCRIPTION.md
  account_analytic_tag/readme/USAGE.md
  account_analytic_tag/security/analytic_security.xml
  account_analytic_tag/security/ir.model.access.csv
  account_analytic_tag/static/description/icon.png
  account_analytic_tag/static/description/index.html
  account_analytic_tag/tests/__init__.py
  account_analytic_tag/tests/common.py
  account_analytic_tag/tests/test_account_analytic_tag.py
  account_analytic_tag/views/account_analytic_line_views.xml
  account_analytic_tag/views/account_analytic_tag_views.xml
  account_analytic_tag/views/account_move_views.xml
  account_analytic_tag/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#642 [16.0][ADD] hr_department_analytic: init
  hr_department_analytic/README.rst
  hr_department_analytic/__init__.py
  hr_department_analytic/__manifest__.py
  hr_department_analytic/models/__init__.py
  hr_department_analytic/models/hr_department.py
  hr_department_analytic/readme/CONTRIBUTORS.md
  hr_department_analytic/readme/DESCRIPTION.md
  hr_department_analytic/static/description/icon.png
  hr_department_analytic/static/description/index.html
  hr_department_analytic/views/hr_department.xml
  setup/hr_department_analytic/odoo/addons/hr_department_analytic
  setup/hr_department_analytic/setup.py
Labels: approved, bot is merging ⏳

#656 [14.0][FIX] stock_analytic: Do not use existing product categories, create new ones.
  stock_analytic/tests/test_stock_picking.py
Labels: approved, bot is merging ⏳

#657 [12.0][ADD] account_analytic_root
  account_analytic_root/README.rst
  account_analytic_root/__init__.py
  account_analytic_root/__manifest__.py
  account_analytic_root/models/__init__.py
  account_analytic_root/models/account_analytic_account.py
  account_analytic_root/readme/DESCRIPTION.rst
  account_analytic_root/static/description/icon.png
  account_analytic_root/tests/__init__.py
  account_analytic_root/tests/test_account_analytic_account.py
  setup/account_analytic_root/odoo/addons/account_analytic_root
  setup/account_analytic_root/setup.py
Labels: bot is merging ⏳

#632 [17.0] [MIG] analytic_base_department
  analytic_base_department/README.rst
  analytic_base_department/__init__.py
  analytic_base_department/__manifest__.py
  analytic_base_department/i18n/analytic_base_department.pot
  analytic_base_department/i18n/ca.po
  analytic_base_department/i18n/de.po
  analytic_base_department/i18n/el_GR.po
  analytic_base_department/i18n/es.po
  analytic_base_department/i18n/es_CO.po
  analytic_base_department/i18n/es_MX.po
  analytic_base_department/i18n/fi.po
  analytic_base_department/i18n/fr.po
  analytic_base_department/i18n/gu_IN.po
  analytic_base_department/i18n/hi_IN.po
  analytic_base_department/i18n/hr_HR.po
  analytic_base_department/i18n/nl.po
  analytic_base_department/i18n/pt.po
  analytic_base_department/i18n/pt_BR.po
  analytic_base_department/i18n/sk_SK.po
  analytic_base_department/i18n/sl.po
  analytic_base_department/i18n/zh_CN.po
  analytic_base_department/models/__init__.py
  analytic_base_department/models/analytic.py
  analytic_base_department/models/hr_department.py
  analytic_base_department/pyproject.toml
  analytic_base_department/readme/CONTRIBUTORS.md
  analytic_base_department/readme/DESCRIPTION.md
  analytic_base_department/readme/HISTORY.md
  analytic_base_department/static/description/icon.png
  analytic_base_department/static/description/index.html
  analytic_base_department/tests/__init__.py
  analytic_base_department/tests/test_line_department.py
  analytic_base_department/views/analytic.xml
  analytic_base_department/views/hr_department_views.xml
Labels: approved, bot is merging ⏳
