Repository OCA/account-analytic, pull requests merged in 2024-03, with the labels that each got.

#610 [16.0][MIG] pos_analytic_by_config: Migration to 16.0
  pos_analytic_by_config/README.rst
  pos_analytic_by_config/__init__.py
  pos_analytic_by_config/__manifest__.py
  pos_analytic_by_config/i18n/ar.po
  pos_analytic_by_config/i18n/ca.po
  pos_analytic_by_config/i18n/de.po
  pos_analytic_by_config/i18n/el_GR.po
  pos_analytic_by_config/i18n/es.po
  pos_analytic_by_config/i18n/es_MX.po
  pos_analytic_by_config/i18n/fi.po
  pos_analytic_by_config/i18n/fr.po
  pos_analytic_by_config/i18n/pos_analytic_by_config.pot
  pos_analytic_by_config/i18n/pt_BR.po
  pos_analytic_by_config/i18n/sk_SK.po
  pos_analytic_by_config/i18n/sl.po
  pos_analytic_by_config/i18n/zh_CN.po
  pos_analytic_by_config/migrations/16.0.1.0.0/post-migration.py
  pos_analytic_by_config/models/__init__.py
  pos_analytic_by_config/models/analytic_distribution_model.py
  pos_analytic_by_config/models/pos_order.py
  pos_analytic_by_config/models/pos_session.py
  pos_analytic_by_config/readme/CONFIGURE.rst
  pos_analytic_by_config/readme/CONTRIBUTORS.rst
  pos_analytic_by_config/readme/DESCRIPTION.rst
  pos_analytic_by_config/readme/ROADMAP.rst
  pos_analytic_by_config/readme/USAGE.rst
  pos_analytic_by_config/static/description/icon.png
  pos_analytic_by_config/static/description/index.html
  pos_analytic_by_config/tests/__init__.py
  pos_analytic_by_config/tests/test_pos_analytic_by_config.py
  pos_analytic_by_config/views/account_analytic_distribution_model_views.xml
  product_analytic/models/account_move.py
  setup/pos_analytic_by_config/odoo/addons/pos_analytic_by_config
  setup/pos_analytic_by_config/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#574 [15.0][FIX] account_tag_dimension: fix permission sudo for allow modify ir.model
  analytic_tag_dimension/models/account_analytic_dimension.py
Labels: bot is merging ⏳

#631 [16.0][IMP] purchase_stock_analyic: propagates values when values are changed even after confirmed PO
  purchase_stock_analytic/models/purchase_order_line.py
Labels: approved, bot is merging ⏳

#608 [15.0][FIX] analytic_partner: fix error expected singleton
  analytic_partner/models/account_move_line.py
Labels: bot is merging ⏳, stale

#576 [MIG][16.0] product_analytic_purchase
  .copier-answers.yml
  .github/workflows/test.yml
  product_analytic_purchase/README.rst
  product_analytic_purchase/__init__.py
  product_analytic_purchase/__manifest__.py
  product_analytic_purchase/i18n/ca.po
  product_analytic_purchase/i18n/cs_CZ.po
  product_analytic_purchase/i18n/es.po
  product_analytic_purchase/i18n/fr.po
  product_analytic_purchase/i18n/hr.po
  product_analytic_purchase/i18n/it.po
  product_analytic_purchase/i18n/product_analytic_purchase.pot
  product_analytic_purchase/models/__init__.py
  product_analytic_purchase/models/purchase_order_line.py
  product_analytic_purchase/readme/CONTRIBUTORS.rst
  product_analytic_purchase/readme/DESCRIPTION.rst
  product_analytic_purchase/readme/USAGE.rst
  product_analytic_purchase/static/description/icon.png
  product_analytic_purchase/static/description/index.html
  product_analytic_purchase/tests/__init__.py
  product_analytic_purchase/tests/test_purchase.py
  setup/product_analytic_purchase/odoo/addons/product_analytic_purchase
  setup/product_analytic_purchase/setup.py
Labels: approved, bot is merging ⏳

#634 [17.0][MIG] account_analytic_parent
  account_analytic_parent/README.rst
  account_analytic_parent/__init__.py
  account_analytic_parent/__manifest__.py
  account_analytic_parent/demo/analytic_account_demo.xml
  account_analytic_parent/hooks.py
  account_analytic_parent/i18n/ab.po
  account_analytic_parent/i18n/account_analytic_parent.pot
  account_analytic_parent/i18n/ca.po
  account_analytic_parent/i18n/cs_CZ.po
  account_analytic_parent/i18n/de.po
  account_analytic_parent/i18n/el_GR.po
  account_analytic_parent/i18n/es.po
  account_analytic_parent/i18n/es_EC.po
  account_analytic_parent/i18n/es_MX.po
  account_analytic_parent/i18n/fi.po
  account_analytic_parent/i18n/fr.po
  account_analytic_parent/i18n/gl.po
  account_analytic_parent/i18n/gl_ES.po
  account_analytic_parent/i18n/gu_IN.po
  account_analytic_parent/i18n/hi_IN.po
  account_analytic_parent/i18n/hr.po
  account_analytic_parent/i18n/hr_HR.po
  account_analytic_parent/i18n/it.po
  account_analytic_parent/i18n/nl.po
  account_analytic_parent/i18n/nl_NL.po
  account_analytic_parent/i18n/pt_BR.po
  account_analytic_parent/i18n/ru.po
  account_analytic_parent/i18n/sk_SK.po
  account_analytic_parent/i18n/sl.po
  account_analytic_parent/i18n/th.po
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_parent/models/__init__.py
  account_analytic_parent/models/account_analytic_account.py
  account_analytic_parent/pyproject.toml
  account_analytic_parent/readme/CONTRIBUTORS.md
  account_analytic_parent/readme/DESCRIPTION.md
  account_analytic_parent/readme/USAGE.md
  account_analytic_parent/static/description/icon.png
  account_analytic_parent/static/description/index.html
  account_analytic_parent/tests/__init__.py
  account_analytic_parent/tests/test_account_analytic_account.py
  account_analytic_parent/views/account_analytic_account_view.xml
Labels: approved, bot is merging ⏳

#622 [16.0][MIG] account_analytic_root
  account_analytic_root/README.rst
  account_analytic_root/__init__.py
  account_analytic_root/__manifest__.py
  account_analytic_root/models/__init__.py
  account_analytic_root/models/account_analytic_account.py
  account_analytic_root/readme/DESCRIPTION.rst
  account_analytic_root/static/description/icon.png
  account_analytic_root/static/description/index.html
  account_analytic_root/tests/__init__.py
  account_analytic_root/tests/test_account_analytic.py
  setup/account_analytic_root/odoo/addons/account_analytic_root
  setup/account_analytic_root/setup.py
Labels: approved, ready to merge, bot is merging ⏳
