Repository OCA/account-analytic, pull requests merged in 2024-10, with the labels that each got.

#691 [16.0][ADD] account_analytic_organization: New module account_analytic_organization
  account_analytic_organization/README.rst
  account_analytic_organization/__init__.py
  account_analytic_organization/__manifest__.py
  account_analytic_organization/i18n/ca_ES.po
  account_analytic_organization/i18n/es.po
  account_analytic_organization/models/__init__.py
  account_analytic_organization/models/account_analytic_line.py
  account_analytic_organization/models/account_analytic_organization.py
  account_analytic_organization/models/account_move_line.py
  account_analytic_organization/models/res_partner.py
  account_analytic_organization/pyproject.toml
  account_analytic_organization/readme/CONTRIBUTORS.md
  account_analytic_organization/readme/DESCRIPTION.md
  account_analytic_organization/readme/USAGE.md
  account_analytic_organization/security/ir.model.access.csv
  account_analytic_organization/static/description/index.html
  account_analytic_organization/views/account_analytic_line.xml
  account_analytic_organization/views/account_analytic_organization.xml
  account_analytic_organization/views/account_move_line.xml
  account_analytic_organization/views/res_partner.xml
  setup/account_analytic_organization/odoo/addons/account_analytic_organization
  setup/account_analytic_organization/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#693 [16.0][IMP] account_analytic_distribution_manual: Add extra json field for export/import to analytic.mixin
  account_analytic_distribution_manual/models/account_analytic_distribution_manual.py
  account_analytic_distribution_manual/models/analytic_mixin.py
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual.py
Labels: approved, ready to merge, bot is merging ⏳

#644 [17.0][MIG] mrp_stock_analytic
  mrp_stock_analytic/README.rst
  mrp_stock_analytic/__init__.py
  mrp_stock_analytic/__manifest__.py
  mrp_stock_analytic/i18n/it.po
  mrp_stock_analytic/i18n/mrp_stock_analytic.pot
  mrp_stock_analytic/models/__init__.py
  mrp_stock_analytic/models/mrp_production.py
  mrp_stock_analytic/pyproject.toml
  mrp_stock_analytic/readme/CONFIGURE.md
  mrp_stock_analytic/readme/CONTRIBUTORS.md
  mrp_stock_analytic/readme/DESCRIPTION.md
  mrp_stock_analytic/readme/USAGE.md
  mrp_stock_analytic/static/description/icon.png
  mrp_stock_analytic/static/description/index.html
  mrp_stock_analytic/tests/__init__.py
  mrp_stock_analytic/tests/test_mrp_stock_analytic.py
  mrp_stock_analytic/views/mrp_production_views.xml
  stock_analytic/tests/test_stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#704 [17.0][MIG] hr_timesheet_analytic_tag: Migration to 17.0
  hr_timesheet_analytic_tag/README.rst
  hr_timesheet_analytic_tag/__init__.py
  hr_timesheet_analytic_tag/__manifest__.py
  hr_timesheet_analytic_tag/i18n/es.po
  hr_timesheet_analytic_tag/i18n/hr_timesheet_analytic_tag.pot
  hr_timesheet_analytic_tag/i18n/it.po
  hr_timesheet_analytic_tag/models/__init__.py
  hr_timesheet_analytic_tag/models/account_analytic_line.py
  hr_timesheet_analytic_tag/models/project_task.py
  hr_timesheet_analytic_tag/pyproject.toml
  hr_timesheet_analytic_tag/readme/CONTRIBUTORS.md
  hr_timesheet_analytic_tag/readme/DESCRIPTION.md
  hr_timesheet_analytic_tag/static/description/icon.png
  hr_timesheet_analytic_tag/static/description/index.html
  hr_timesheet_analytic_tag/tests/__init__.py
  hr_timesheet_analytic_tag/tests/test_hr_timesheet_analytic_tag.py
  hr_timesheet_analytic_tag/views/project_task_view.xml
Labels: approved, bot is merging ⏳

#703 [16.0][FIX] stock_analytic
  stock_analytic/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#706 [17.0][FIX] stock_analytic: fix analytic_distribution transfer from move to move Line
  stock_analytic/models/stock_move.py
Labels: approved, bot is merging ⏳

#692 [FIX] account_analytic_required: make field non-company-dependant
  account_analytic_required/README.rst
  account_analytic_required/__manifest__.py
  account_analytic_required/migrations/16.0.2.0.0/post-migrate.py
  account_analytic_required/models/account.py
  account_analytic_required/readme/CONTRIBUTORS.rst
  account_analytic_required/readme/DESCRIPTION.rst
  account_analytic_required/static/description/index.html
  account_analytic_required/tests/test_account_analytic_required.py
Labels: needs review, approved, bot is merging ⏳
