Repository OCA/account-analytic, pull requests merged in 2024-11, with the labels that each got.

#652 [17.0][MIG] pos_analytic_by_config: Migration to 17.0
  pos_analytic_by_config/README.rst
  pos_analytic_by_config/__init__.py
  pos_analytic_by_config/__manifest__.py
  pos_analytic_by_config/i18n/ar.po
  pos_analytic_by_config/i18n/ca.po
  pos_analytic_by_config/i18n/de.po
  pos_analytic_by_config/i18n/el_GR.po
  pos_analytic_by_config/i18n/es.po
  pos_analytic_by_config/i18n/es_MX.po
  pos_analytic_by_config/i18n/fi.po
  pos_analytic_by_config/i18n/fr.po
  pos_analytic_by_config/i18n/it.po
  pos_analytic_by_config/i18n/pos_analytic_by_config.pot
  pos_analytic_by_config/i18n/pt_BR.po
  pos_analytic_by_config/i18n/sk_SK.po
  pos_analytic_by_config/i18n/sl.po
  pos_analytic_by_config/i18n/zh_CN.po
  pos_analytic_by_config/models/__init__.py
  pos_analytic_by_config/models/analytic_distribution_model.py
  pos_analytic_by_config/models/pos_order.py
  pos_analytic_by_config/models/pos_session.py
  pos_analytic_by_config/pyproject.toml
  pos_analytic_by_config/readme/CONFIGURE.md
  pos_analytic_by_config/readme/CONTRIBUTORS.md
  pos_analytic_by_config/readme/DESCRIPTION.md
  pos_analytic_by_config/readme/ROADMAP.md
  pos_analytic_by_config/readme/USAGE.md
  pos_analytic_by_config/static/description/icon.png
  pos_analytic_by_config/static/description/index.html
  pos_analytic_by_config/tests/__init__.py
  pos_analytic_by_config/tests/test_pos_analytic_by_config.py
  pos_analytic_by_config/views/account_analytic_distribution_model_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#709 [18.0][MIG] account_analytic_tag: Migration to 18.0
  account_analytic_tag/README.rst
  account_analytic_tag/__init__.py
  account_analytic_tag/__manifest__.py
  account_analytic_tag/i18n/account_analytic_tag.pot
  account_analytic_tag/i18n/ca.po
  account_analytic_tag/i18n/en_US.po
  account_analytic_tag/i18n/es.po
  account_analytic_tag/i18n/it.po
  account_analytic_tag/i18n/pt_BR.po
  account_analytic_tag/i18n/zh_CN.po
  account_analytic_tag/models/__init__.py
  account_analytic_tag/models/account_analytic_line.py
  account_analytic_tag/models/account_analytic_tag.py
  account_analytic_tag/models/account_move_line.py
  account_analytic_tag/models/res_config_settings.py
  account_analytic_tag/pyproject.toml
  account_analytic_tag/readme/CONFIGURE.md
  account_analytic_tag/readme/CONTRIBUTORS.md
  account_analytic_tag/readme/DESCRIPTION.md
  account_analytic_tag/readme/USAGE.md
  account_analytic_tag/security/analytic_security.xml
  account_analytic_tag/security/ir.model.access.csv
  account_analytic_tag/static/description/icon.png
  account_analytic_tag/static/description/index.html
  account_analytic_tag/tests/__init__.py
  account_analytic_tag/tests/common.py
  account_analytic_tag/tests/test_account_analytic_tag.py
  account_analytic_tag/views/account_analytic_line_views.xml
  account_analytic_tag/views/account_analytic_tag_views.xml
  account_analytic_tag/views/account_move_views.xml
  account_analytic_tag/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#711 [18.0][MIG] hr_timesheet_analytic_tag: Migration to 18.0
  hr_timesheet_analytic_tag/README.rst
  hr_timesheet_analytic_tag/__init__.py
  hr_timesheet_analytic_tag/__manifest__.py
  hr_timesheet_analytic_tag/i18n/es.po
  hr_timesheet_analytic_tag/i18n/hr_timesheet_analytic_tag.pot
  hr_timesheet_analytic_tag/i18n/it.po
  hr_timesheet_analytic_tag/models/__init__.py
  hr_timesheet_analytic_tag/models/account_analytic_line.py
  hr_timesheet_analytic_tag/models/project_task.py
  hr_timesheet_analytic_tag/pyproject.toml
  hr_timesheet_analytic_tag/readme/CONTRIBUTORS.md
  hr_timesheet_analytic_tag/readme/DESCRIPTION.md
  hr_timesheet_analytic_tag/static/description/icon.png
  hr_timesheet_analytic_tag/static/description/index.html
  hr_timesheet_analytic_tag/tests/__init__.py
  hr_timesheet_analytic_tag/tests/test_hr_timesheet_analytic_tag.py
  hr_timesheet_analytic_tag/views/project_task_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#698 [18.0][MIG] account_analytic_parent: Migration to 18.0
  account_analytic_parent/README.rst
  account_analytic_parent/__init__.py
  account_analytic_parent/__manifest__.py
  account_analytic_parent/demo/analytic_account_demo.xml
  account_analytic_parent/hooks.py
  account_analytic_parent/i18n/ab.po
  account_analytic_parent/i18n/account_analytic_parent.pot
  account_analytic_parent/i18n/ca.po
  account_analytic_parent/i18n/cs_CZ.po
  account_analytic_parent/i18n/de.po
  account_analytic_parent/i18n/el_GR.po
  account_analytic_parent/i18n/es.po
  account_analytic_parent/i18n/es_EC.po
  account_analytic_parent/i18n/es_MX.po
  account_analytic_parent/i18n/fi.po
  account_analytic_parent/i18n/fr.po
  account_analytic_parent/i18n/gl.po
  account_analytic_parent/i18n/gl_ES.po
  account_analytic_parent/i18n/gu_IN.po
  account_analytic_parent/i18n/hi_IN.po
  account_analytic_parent/i18n/hr.po
  account_analytic_parent/i18n/hr_HR.po
  account_analytic_parent/i18n/it.po
  account_analytic_parent/i18n/nl.po
  account_analytic_parent/i18n/nl_NL.po
  account_analytic_parent/i18n/pt_BR.po
  account_analytic_parent/i18n/ru.po
  account_analytic_parent/i18n/sk_SK.po
  account_analytic_parent/i18n/sl.po
  account_analytic_parent/i18n/th.po
  account_analytic_parent/i18n/zh_CN.po
  account_analytic_parent/models/__init__.py
  account_analytic_parent/models/account_analytic_account.py
  account_analytic_parent/pyproject.toml
  account_analytic_parent/readme/CONTRIBUTORS.md
  account_analytic_parent/readme/DESCRIPTION.md
  account_analytic_parent/readme/USAGE.md
  account_analytic_parent/static/description/icon.png
  account_analytic_parent/static/description/index.html
  account_analytic_parent/tests/__init__.py
  account_analytic_parent/tests/test_account_analytic_account.py
  account_analytic_parent/views/account_analytic_account_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#716 [16.0][FIX] hr_expense_analytic_tag: Fix + improve tests
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
Labels: bot is merging ⏳

#717 [16.0][IMP] account_analytic_tag: Add analytic tags field to journal items tree view
  account_analytic_tag/__manifest__.py
  account_analytic_tag/views/account_move_line_views.xml
Labels: approved, bot is merging ⏳

#718 [17.0][IMP] account_analytic_tag: Add analytic tags field to journal items tree view
  account_analytic_tag/__manifest__.py
  account_analytic_tag/views/account_move_line_views.xml
Labels: approved, bot is merging ⏳

#719 [18.0][IMP] account_analytic_tag: Add analytic tags field to journal items tree view
  account_analytic_tag/__manifest__.py
  account_analytic_tag/views/account_move_line_views.xml
Labels: approved, bot is merging ⏳
