Repository OCA/account-analytic, pull requests merged in 2024-09, with the labels that each got.

#685 [16.0][IMP] account_analytic_distribution_manual: Add extra json field for export/import of analytical distributions
  account_analytic_distribution_manual/models/account_analytic_distribution_manual.py
  account_analytic_distribution_manual/tests/__init__.py
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual.py
Labels: approved, bot is merging ⏳

#682 [17.0][REF] stock_analytic: Split test utilities into shareable base class
  stock_analytic/tests/test_stock_picking.py
Labels: approved, bot is merging ⏳

#655 [17.0] [ADD] account_analytic_spread_by_tag: New module
  account_analytic_spread_by_tag/README.rst
  account_analytic_spread_by_tag/__init__.py
  account_analytic_spread_by_tag/__manifest__.py
  account_analytic_spread_by_tag/i18n/ca_ES.po
  account_analytic_spread_by_tag/i18n/en_US.po
  account_analytic_spread_by_tag/i18n/es.po
  account_analytic_spread_by_tag/models/__init__.py
  account_analytic_spread_by_tag/models/account_analytic_account.py
  account_analytic_spread_by_tag/models/account_analytic_tag.py
  account_analytic_spread_by_tag/models/account_move_line.py
  account_analytic_spread_by_tag/pyproject.toml
  account_analytic_spread_by_tag/readme/CONFIGURE.md
  account_analytic_spread_by_tag/readme/CONTRIBUTORS.md
  account_analytic_spread_by_tag/readme/DESCRIPTION.md
  account_analytic_spread_by_tag/readme/ROADMAP.md
  account_analytic_spread_by_tag/readme/USAGE.md
  account_analytic_spread_by_tag/static/description/icon.png
  account_analytic_spread_by_tag/static/description/index.html
  account_analytic_spread_by_tag/static/img/image.png
  account_analytic_spread_by_tag/static/img/image2.png
  account_analytic_spread_by_tag/static/img/image3.png
  account_analytic_spread_by_tag/tests/__init__.py
  account_analytic_spread_by_tag/tests/common.py
  account_analytic_spread_by_tag/tests/test_account_analytic_spread.py
  account_analytic_spread_by_tag/views/account_analytic_account_views.xml
  account_analytic_spread_by_tag/views/account_analytic_tag_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#648 [14.0] account_analytic_no_lines: add migration script
  account_analytic_no_lines/migrations/14.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳, stale

#688 [16.0][IMP] account_analytic_distribution_manual: Add manual_distribution_id field to analytic items
  account_analytic_distribution_manual/__manifest__.py
  account_analytic_distribution_manual/hooks.py
  account_analytic_distribution_manual/migrations/16.0.2.3.0/post-migration.py
  account_analytic_distribution_manual/models/__init__.py
  account_analytic_distribution_manual/models/account_analytic_line.py
  account_analytic_distribution_manual/models/account_move_line.py
  account_analytic_distribution_manual/static/description/index.html
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual.py
  account_analytic_distribution_manual/views/account_analytic_line_views.xml
Labels: approved, bot is merging ⏳
