Repository OCA/account-analytic, pull requests merged in 2024-08, with the labels that each got.

#658 [16.0][MIG] analytic_base_department
  analytic_base_department/README.rst
  analytic_base_department/__init__.py
  analytic_base_department/__manifest__.py
  analytic_base_department/i18n/analytic_base_department.pot
  analytic_base_department/i18n/ca.po
  analytic_base_department/i18n/de.po
  analytic_base_department/i18n/el_GR.po
  analytic_base_department/i18n/es.po
  analytic_base_department/i18n/es_CO.po
  analytic_base_department/i18n/es_MX.po
  analytic_base_department/i18n/fi.po
  analytic_base_department/i18n/fr.po
  analytic_base_department/i18n/gu_IN.po
  analytic_base_department/i18n/hi_IN.po
  analytic_base_department/i18n/hr_HR.po
  analytic_base_department/i18n/nl.po
  analytic_base_department/i18n/pt.po
  analytic_base_department/i18n/pt_BR.po
  analytic_base_department/i18n/sk_SK.po
  analytic_base_department/i18n/sl.po
  analytic_base_department/i18n/zh_CN.po
  analytic_base_department/models/__init__.py
  analytic_base_department/models/analytic.py
  analytic_base_department/models/hr_department.py
  analytic_base_department/readme/CONTRIBUTORS.rst
  analytic_base_department/readme/DESCRIPTION.rst
  analytic_base_department/readme/HISTORY.rst
  analytic_base_department/static/description/icon.png
  analytic_base_department/static/description/index.html
  analytic_base_department/tests/__init__.py
  analytic_base_department/tests/test_line_department.py
  analytic_base_department/views/analytic.xml
  analytic_base_department/views/hr_department_views.xml
  setup/analytic_base_department/odoo/addons/analytic_base_department
  setup/analytic_base_department/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#614 [17.0][MIG] stock analytic: Migration to 17.0
  stock_analytic/README.rst
  stock_analytic/__init__.py
  stock_analytic/__manifest__.py
  stock_analytic/i18n/ca.po
  stock_analytic/i18n/cs_CZ.po
  stock_analytic/i18n/de.po
  stock_analytic/i18n/el_GR.po
  stock_analytic/i18n/es.po
  stock_analytic/i18n/es_EC.po
  stock_analytic/i18n/es_MX.po
  stock_analytic/i18n/fi.po
  stock_analytic/i18n/fr.po
  stock_analytic/i18n/gl.po
  stock_analytic/i18n/gu_IN.po
  stock_analytic/i18n/hi_IN.po
  stock_analytic/i18n/hr.po
  stock_analytic/i18n/hr_HR.po
  stock_analytic/i18n/hu.po
  stock_analytic/i18n/it.po
  stock_analytic/i18n/nl.po
  stock_analytic/i18n/pt.po
  stock_analytic/i18n/pt_BR.po
  stock_analytic/i18n/pt_PT.po
  stock_analytic/i18n/ro.po
  stock_analytic/i18n/sk_SK.po
  stock_analytic/i18n/sl.po
  stock_analytic/i18n/stock_analytic.pot
  stock_analytic/i18n/tr.po
  stock_analytic/i18n/tr_TR.po
  stock_analytic/i18n/vi_VN.po
  stock_analytic/i18n/zh_CN.po
  stock_analytic/models/__init__.py
  stock_analytic/models/analytic_applicability.py
  stock_analytic/models/stock_move.py
  stock_analytic/models/stock_picking.py
  stock_analytic/models/stock_rule.py
  stock_analytic/models/stock_scrap.py
  stock_analytic/pyproject.toml
  stock_analytic/readme/CONFIGURE.md
  stock_analytic/readme/CONTRIBUTORS.md
  stock_analytic/readme/DESCRIPTION.md
  stock_analytic/readme/USAGE.md
  stock_analytic/static/description/icon.png
  stock_analytic/static/description/index.html
  stock_analytic/tests/__init__.py
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/tests/test_stock_scrap.py
  stock_analytic/views/stock_move_line_views.xml
  stock_analytic/views/stock_move_views.xml
  stock_analytic/views/stock_picking_views.xml
  stock_analytic/views/stock_scrap_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#641 [16.0][IMP] stock_analytic: salvage analytic distribution from procurement
  stock_analytic/models/__init__.py
  stock_analytic/models/stock_rule.py
  stock_analytic/tests/test_stock_picking.py
Labels: approved, ready to merge, bot is merging ⏳

#677 [16.0][IMP] account_analytic_distribution_manual: Enhanced control of analytics account from manual distribution
  account_analytic_distribution_manual/README.rst
  account_analytic_distribution_manual/__init__.py
  account_analytic_distribution_manual/__manifest__.py
  account_analytic_distribution_manual/hooks.py
  account_analytic_distribution_manual/models/__init__.py
  account_analytic_distribution_manual/models/account_analytic_distribution_manual.py
  account_analytic_distribution_manual/models/analytic_mixin.py
  account_analytic_distribution_manual/models/base.py
  account_analytic_distribution_manual/readme/CONFIGURE.rst
  account_analytic_distribution_manual/readme/ROADMAP.rst
  account_analytic_distribution_manual/static/description/index.html
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.xml
  account_analytic_distribution_manual/static/src/tests/tours/account_analytic_distribution_manual.esm.js
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual_tour.py
Labels: approved, bot is merging ⏳

#679 [16.0][IMP] account_analytic_distribution_manual: change field type from integer to many2one
  account_analytic_distribution_manual/hooks.py
  account_analytic_distribution_manual/models/analytic_mixin.py
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
Labels: approved, bot is merging ⏳

#680 [16.0][FIX] account_analytic_required: remove unneeded dependency
  account_analytic_required/__manifest__.py
Labels: needs review, approved, bot is merging ⏳

#665 [16.0][FIX] stock_analytic: use standard method to get stock valuation account
  stock_analytic/models/stock_move.py
Labels: approved, ready to merge, bot is merging ⏳

#676 [17.0][MIG] stock_picking_analytic: Migration to 17.0
  stock_picking_analytic/README.rst
  stock_picking_analytic/__init__.py
  stock_picking_analytic/__manifest__.py
  stock_picking_analytic/i18n/es.po
  stock_picking_analytic/i18n/it.po
  stock_picking_analytic/i18n/pt_BR.po
  stock_picking_analytic/i18n/stock_picking_analytic.pot
  stock_picking_analytic/models/__init__.py
  stock_picking_analytic/models/stock_picking.py
  stock_picking_analytic/pyproject.toml
  stock_picking_analytic/readme/CONTRIBUTORS.md
  stock_picking_analytic/readme/DESCRIPTION.md
  stock_picking_analytic/static/description/icon.png
  stock_picking_analytic/static/description/index.html
  stock_picking_analytic/tests/__init__.py
  stock_picking_analytic/tests/test_picking_analytic_account.py
  stock_picking_analytic/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#684 [16.0] [IMP] account_analytic_distribution_manual: add field manual_distribution_id into account.invoice.report
  account_analytic_distribution_manual/__init__.py
  account_analytic_distribution_manual/reports/__init__.py
  account_analytic_distribution_manual/reports/invoice_report.py
Labels: approved, bot is merging ⏳
