Repository OCA/account-analytic, pull requests merged in 2025-03, with the labels that each got.

#751 [16.0][FIX] sale_analytic_tag: Post-install test + fallback to load CoA
  sale_analytic_tag/tests/test_sale_analytic_tag.py
Labels: bot is merging ⏳

#565 [16.0][ADD] analytic_mixin_analytic_account
  analytic_mixin_analytic_account/README.rst
  analytic_mixin_analytic_account/__init__.py
  analytic_mixin_analytic_account/__manifest__.py
  analytic_mixin_analytic_account/i18n/ja.po
  analytic_mixin_analytic_account/models/__init__.py
  analytic_mixin_analytic_account/models/analytic_mixin.py
  analytic_mixin_analytic_account/readme/CONTRIBUTORS.rst
  analytic_mixin_analytic_account/readme/DESCRIPTION.rst
  analytic_mixin_analytic_account/static/description/index.html
  analytic_mixin_analytic_account/tests/__init__.py
  analytic_mixin_analytic_account/tests/test_analytic_mixin_analytic_account.py
  setup/analytic_mixin_analytic_account/odoo/addons/analytic_mixin_analytic_account
  setup/analytic_mixin_analytic_account/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#752 [15.0][FIX] account_analytic_tag_default: analytic_tag_ids is computed in standard
  account_analytic_tag_default/README.rst
  account_analytic_tag_default/models/account_move.py
  account_analytic_tag_default/readme/ROADMAP.rst
  account_analytic_tag_default/static/description/index.html
Labels: approved, bot is merging ⏳

#755 [17.0][IMP] account_analytic_distribution_manual: Improved performance of the analytic accounts search
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
Labels: approved, bot is merging ⏳
