Repository OCA/account-analytic, pull requests merged in 2025-04, with the labels that each got.

#715 [17.0][MIG] purchase_analytic_tag: Migration to 17.0
  purchase_analytic_tag/README.rst
  purchase_analytic_tag/__init__.py
  purchase_analytic_tag/__manifest__.py
  purchase_analytic_tag/i18n/es.po
  purchase_analytic_tag/i18n/it.po
  purchase_analytic_tag/i18n/purchase_analytic_tag.pot
  purchase_analytic_tag/models/__init__.py
  purchase_analytic_tag/models/purchase_order_line.py
  purchase_analytic_tag/pyproject.toml
  purchase_analytic_tag/readme/CONTRIBUTORS.md
  purchase_analytic_tag/readme/DESCRIPTION.md
  purchase_analytic_tag/static/description/icon.png
  purchase_analytic_tag/static/description/index.html
  purchase_analytic_tag/tests/__init__.py
  purchase_analytic_tag/tests/test_purchase_analytic_tag.py
  purchase_analytic_tag/views/purchase_oder_view.xml
Labels: approved, ready to merge, bot is merging ⏳, stale

#702 [17.0][ADD] account_analytic_distribution_manual_date: New module account_analytic_distribution_manual_date
  account_analytic_distribution_manual_date/README.rst
  account_analytic_distribution_manual_date/__init__.py
  account_analytic_distribution_manual_date/__manifest__.py
  account_analytic_distribution_manual_date/i18n/ca.po
  account_analytic_distribution_manual_date/i18n/es .po
  account_analytic_distribution_manual_date/models/__init__.py
  account_analytic_distribution_manual_date/models/account_analytic_distribution_manual.py
  account_analytic_distribution_manual_date/models/account_move.py
  account_analytic_distribution_manual_date/pyproject.toml
  account_analytic_distribution_manual_date/readme/CONTRIBUTORS.md
  account_analytic_distribution_manual_date/readme/DESCRIPTION.md
  account_analytic_distribution_manual_date/readme/USAGE.md
  account_analytic_distribution_manual_date/static/description/icon.png
  account_analytic_distribution_manual_date/static/description/index.html
  account_analytic_distribution_manual_date/static/src/components/analytic_distribution/analytic_distribution.esm.js
  account_analytic_distribution_manual_date/tests/__init__.py
  account_analytic_distribution_manual_date/tests/test_manual_distribution_date.py
  account_analytic_distribution_manual_date/views/account_analytic_distribution_manual_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#766 [16.0][IMP] hr_expense_analytic_tag: Add analytical tags to company-paid expense records
  hr_expense_analytic_tag/models/hr_expense.py
  hr_expense_analytic_tag/tests/test_hr_expense_analytic_tag.py
Labels: approved, bot is merging ⏳

#769 [18.0][MIG] account_analytic_distribution_manual: Migration to version 18.0
  account_analytic_distribution_manual/README.rst
  account_analytic_distribution_manual/__init__.py
  account_analytic_distribution_manual/__manifest__.py
  account_analytic_distribution_manual/i18n/account_analytic_distribution_manual.pot
  account_analytic_distribution_manual/i18n/ca.po
  account_analytic_distribution_manual/i18n/es.po
  account_analytic_distribution_manual/i18n/it.po
  account_analytic_distribution_manual/models/__init__.py
  account_analytic_distribution_manual/models/account_analytic_distribution_manual.py
  account_analytic_distribution_manual/models/account_analytic_line.py
  account_analytic_distribution_manual/models/account_move_line.py
  account_analytic_distribution_manual/models/analytic_mixin.py
  account_analytic_distribution_manual/models/base.py
  account_analytic_distribution_manual/pyproject.toml
  account_analytic_distribution_manual/readme/CONFIGURE.md
  account_analytic_distribution_manual/readme/CONTRIBUTORS.md
  account_analytic_distribution_manual/readme/DESCRIPTION.md
  account_analytic_distribution_manual/readme/ROADMAP.md
  account_analytic_distribution_manual/readme/USAGE.md
  account_analytic_distribution_manual/reports/__init__.py
  account_analytic_distribution_manual/reports/invoice_report.py
  account_analytic_distribution_manual/security/analytic_security.xml
  account_analytic_distribution_manual/security/ir.model.access.csv
  account_analytic_distribution_manual/static/description/icon.png
  account_analytic_distribution_manual/static/description/index.html
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
  account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.xml
  account_analytic_distribution_manual/static/src/tests/tours/account_analytic_distribution_manual.esm.js
  account_analytic_distribution_manual/tests/__init__.py
  account_analytic_distribution_manual/tests/common.py
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual.py
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual_tour.py
  account_analytic_distribution_manual/views/account_analytic_distribution_manual_views.xml
  account_analytic_distribution_manual/views/account_analytic_line_views.xml
Labels: approved, bot is merging ⏳
