Repository OCA/account-analytic, pull requests merged in 2025-06, with the labels that each got.

#759 [18.0][MIG] purchase_analytic_tag
  purchase_analytic_tag/README.rst
  purchase_analytic_tag/__init__.py
  purchase_analytic_tag/__manifest__.py
  purchase_analytic_tag/i18n/es.po
  purchase_analytic_tag/i18n/it.po
  purchase_analytic_tag/i18n/purchase_analytic_tag.pot
  purchase_analytic_tag/models/__init__.py
  purchase_analytic_tag/models/purchase_order_line.py
  purchase_analytic_tag/pyproject.toml
  purchase_analytic_tag/readme/CONTRIBUTORS.md
  purchase_analytic_tag/readme/DESCRIPTION.md
  purchase_analytic_tag/static/description/icon.png
  purchase_analytic_tag/static/description/index.html
  purchase_analytic_tag/tests/__init__.py
  purchase_analytic_tag/tests/test_purchase_analytic_tag.py
  purchase_analytic_tag/views/purchase_oder_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#784 [ADD] crm_claim_analytic: new module
  crm_claim_analytic/README.rst
  crm_claim_analytic/__init__.py
  crm_claim_analytic/__manifest__.py
  crm_claim_analytic/i18n/crm_claim_analytic.pot
  crm_claim_analytic/i18n/es.po
  crm_claim_analytic/models/__init__.py
  crm_claim_analytic/models/account_analytic_account.py
  crm_claim_analytic/models/account_analytic_line.py
  crm_claim_analytic/models/crm_claim.py
  crm_claim_analytic/readme/CONTRIBUTORS.rst
  crm_claim_analytic/readme/DESCRIPTION.rst
  crm_claim_analytic/readme/USAGE.rst
  crm_claim_analytic/static/description/icon.png
  crm_claim_analytic/static/description/index.html
  crm_claim_analytic/tests/__init__.py
  crm_claim_analytic/tests/test_crm_claim_analytic.py
  crm_claim_analytic/views/account_analytic_account_views.xml
  crm_claim_analytic/views/account_analytic_line_views.xml
  crm_claim_analytic/views/crm_claim_views.xml
  setup/crm_claim_analytic/odoo/addons/crm_claim_analytic
  setup/crm_claim_analytic/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#586 [16.0][IMP] stock_analytic: more granularity on applicability judgment
  stock_analytic/README.rst
  stock_analytic/__manifest__.py
  stock_analytic/models/analytic_applicability.py
  stock_analytic/models/stock_move.py
  stock_analytic/readme/USAGE.rst
  stock_analytic/static/description/index.html
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/views/account_analytic_plan_views.xml
Labels: needs review, approved, bot is merging ⏳, no stale

#767 [17.0] [ADD] account_analytic_distribution_widget_rebalance
  account_analytic_distribution_widget_rebalance/README.rst
  account_analytic_distribution_widget_rebalance/__init__.py
  account_analytic_distribution_widget_rebalance/__manifest__.py
  account_analytic_distribution_widget_rebalance/pyproject.toml
  account_analytic_distribution_widget_rebalance/readme/CONTRIBUTORS.md
  account_analytic_distribution_widget_rebalance/readme/DESCRIPTION.md
  account_analytic_distribution_widget_rebalance/readme/USAGE.md
  account_analytic_distribution_widget_rebalance/static/description/index.html
  account_analytic_distribution_widget_rebalance/static/img/step1.png
  account_analytic_distribution_widget_rebalance/static/img/step2.png
  account_analytic_distribution_widget_rebalance/static/img/step3.png
  account_analytic_distribution_widget_rebalance/static/src/AnalyticDistribution.esm.js
  account_analytic_distribution_widget_rebalance/static/src/AnalyticDistribution.scss
  account_analytic_distribution_widget_rebalance/static/src/AnalyticDistribution.xml
  account_analytic_distribution_widget_rebalance/static/tests/AnalyticDistribution.esm.js
  account_analytic_distribution_widget_rebalance/tests/__init__.py
  account_analytic_distribution_widget_rebalance/tests/test_qunit.py
Labels: approved, ready to merge, bot is merging ⏳

#797 [18.0][IMP] analytic_hr_department_restriction: Convert department_id to department_ids
  analytic_hr_department_restriction/README.rst
  analytic_hr_department_restriction/__manifest__.py
  analytic_hr_department_restriction/migrations/18.0.1.1.0/post-migration.py
  analytic_hr_department_restriction/models/account_analytic_account.py
  analytic_hr_department_restriction/models/account_analytic_plan.py
  analytic_hr_department_restriction/models/ir_rule.py
  analytic_hr_department_restriction/tests/test_analytic_hr_department_restriction.py
  analytic_hr_department_restriction/views/account_analytic_account_views.xml
  analytic_hr_department_restriction/views/account_analytic_plan_views.xml
Labels: approved, bot is merging ⏳

#798 [IMP] stock_analytic: more granularity on applicability judgment
  stock_analytic/README.rst
  stock_analytic/__manifest__.py
  stock_analytic/models/analytic_applicability.py
  stock_analytic/models/stock_move.py
  stock_analytic/readme/USAGE.md
  stock_analytic/static/description/index.html
  stock_analytic/tests/test_stock_picking.py
  stock_analytic/views/account_analytic_plan_views.xml
Labels: bot is merging ⏳

#795 [17.0][IMP] account_analytic_distribution_model_recalculate: Added button to sync journal items with the distribution model
  account_analytic_distribution_model_recalculate/README.rst
  account_analytic_distribution_model_recalculate/i18n/ca.po
  account_analytic_distribution_model_recalculate/i18n/es.po
  account_analytic_distribution_model_recalculate/models/account_analytic_distribution_model.py
  account_analytic_distribution_model_recalculate/readme/USAGE.md
  account_analytic_distribution_model_recalculate/static/description/index.html
  account_analytic_distribution_model_recalculate/tests/test_account_analytic_distribution_model.py
  account_analytic_distribution_model_recalculate/views/account_analytic_distribution_model.xml
Labels: approved, bot is merging ⏳

#801 [17.0] [MIG] account_analytic_organization: Migration to 17.0
  account_analytic_organization/README.rst
  account_analytic_organization/__init__.py
  account_analytic_organization/__manifest__.py
  account_analytic_organization/i18n/account_analytic_organization.pot
  account_analytic_organization/i18n/ca.po
  account_analytic_organization/i18n/es.po
  account_analytic_organization/i18n/it.po
  account_analytic_organization/models/__init__.py
  account_analytic_organization/models/account_analytic_line.py
  account_analytic_organization/models/account_analytic_organization.py
  account_analytic_organization/models/account_move_line.py
  account_analytic_organization/models/res_partner.py
  account_analytic_organization/pyproject.toml
  account_analytic_organization/readme/CONTRIBUTORS.md
  account_analytic_organization/readme/DESCRIPTION.md
  account_analytic_organization/readme/USAGE.md
  account_analytic_organization/security/ir.model.access.csv
  account_analytic_organization/static/description/icon.png
  account_analytic_organization/static/description/index.html
  account_analytic_organization/views/account_analytic_line.xml
  account_analytic_organization/views/account_analytic_organization.xml
  account_analytic_organization/views/account_move_line.xml
  account_analytic_organization/views/res_partner.xml
Labels: approved, bot is merging ⏳
