Repository OCA/account-analytic, pull requests merged in 2025-05, with the labels that each got.

#757 [16.0][ADD] analytic_hr_department_restriction: New module
  analytic_hr_department_restriction/README.rst
  analytic_hr_department_restriction/__init__.py
  analytic_hr_department_restriction/__manifest__.py
  analytic_hr_department_restriction/i18n/analytic_hr_department_restriction.pot
  analytic_hr_department_restriction/i18n/es.po
  analytic_hr_department_restriction/models/__init__.py
  analytic_hr_department_restriction/models/account_analytic_account.py
  analytic_hr_department_restriction/models/account_analytic_plan.py
  analytic_hr_department_restriction/models/ir_rule.py
  analytic_hr_department_restriction/readme/CONFIGURE.rst
  analytic_hr_department_restriction/readme/CONTRIBUTORS.rst
  analytic_hr_department_restriction/readme/DESCRIPTION.rst
  analytic_hr_department_restriction/readme/USAGE.rst
  analytic_hr_department_restriction/security/groups.xml
  analytic_hr_department_restriction/static/description/icon.png
  analytic_hr_department_restriction/static/description/index.html
  analytic_hr_department_restriction/tests/__init__.py
  analytic_hr_department_restriction/tests/test_analytic_hr_department_restriction.py
  analytic_hr_department_restriction/views/account_analytic_account_views.xml
  analytic_hr_department_restriction/views/account_analytic_plan_views.xml
  setup/analytic_hr_department_restriction/odoo/addons/analytic_hr_department_restriction
  setup/analytic_hr_department_restriction/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#777 [18.0][MIG] account_analytic_spread_by_tag: Migration to 18.0
  account_analytic_spread_by_tag/README.rst
  account_analytic_spread_by_tag/__init__.py
  account_analytic_spread_by_tag/__manifest__.py
  account_analytic_spread_by_tag/i18n/account_analytic_spread_by_tag.pot
  account_analytic_spread_by_tag/i18n/ca_ES.po
  account_analytic_spread_by_tag/i18n/en_US.po
  account_analytic_spread_by_tag/i18n/es.po
  account_analytic_spread_by_tag/i18n/it.po
  account_analytic_spread_by_tag/models/__init__.py
  account_analytic_spread_by_tag/models/account_analytic_account.py
  account_analytic_spread_by_tag/models/account_analytic_tag.py
  account_analytic_spread_by_tag/models/account_move_line.py
  account_analytic_spread_by_tag/pyproject.toml
  account_analytic_spread_by_tag/readme/CONFIGURE.md
  account_analytic_spread_by_tag/readme/CONTRIBUTORS.md
  account_analytic_spread_by_tag/readme/DESCRIPTION.md
  account_analytic_spread_by_tag/readme/ROADMAP.md
  account_analytic_spread_by_tag/readme/USAGE.md
  account_analytic_spread_by_tag/static/description/icon.png
  account_analytic_spread_by_tag/static/description/index.html
  account_analytic_spread_by_tag/static/img/image.png
  account_analytic_spread_by_tag/static/img/image2.png
  account_analytic_spread_by_tag/static/img/image3.png
  account_analytic_spread_by_tag/tests/__init__.py
  account_analytic_spread_by_tag/tests/common.py
  account_analytic_spread_by_tag/tests/test_account_analytic_spread.py
  account_analytic_spread_by_tag/views/account_analytic_account_views.xml
  account_analytic_spread_by_tag/views/account_analytic_tag_views.xml
Labels: approved, bot is merging ⏳

#779 [16.0][IMP] analytic_hr_department_restriction: Multi-company compatibility
  analytic_hr_department_restriction/models/ir_rule.py
  analytic_hr_department_restriction/tests/test_analytic_hr_department_restriction.py
Labels: approved, bot is merging ⏳

#783 [17.0][mig] purchase_stock_analytic
  purchase_stock_analytic/README.rst
  purchase_stock_analytic/__init__.py
  purchase_stock_analytic/__manifest__.py
  purchase_stock_analytic/i18n/es.po
  purchase_stock_analytic/i18n/pt_BR.po
  purchase_stock_analytic/i18n/purchase_stock_analytic.pot
  purchase_stock_analytic/models/__init__.py
  purchase_stock_analytic/models/purchase_order_line.py
  purchase_stock_analytic/pyproject.toml
  purchase_stock_analytic/readme/DESCRIPTION.md
  purchase_stock_analytic/readme/USAGE.md
  purchase_stock_analytic/static/description/icon.png
  purchase_stock_analytic/static/description/index.html
  purchase_stock_analytic/tests/__init__.py
  purchase_stock_analytic/tests/test_purchase_stock_analytic.py
Labels: needs review, bot is merging ⏳

#778 [18.0][MIG] analytic_hr_department_restriction: Migration to 18.0
  analytic_hr_department_restriction/README.rst
  analytic_hr_department_restriction/__init__.py
  analytic_hr_department_restriction/__manifest__.py
  analytic_hr_department_restriction/i18n/analytic_hr_department_restriction.pot
  analytic_hr_department_restriction/i18n/es.po
  analytic_hr_department_restriction/migrations/18.0.1.0.0/post-migration.py
  analytic_hr_department_restriction/migrations/18.0.1.0.0/pre-migration.py
  analytic_hr_department_restriction/models/__init__.py
  analytic_hr_department_restriction/models/account_analytic_account.py
  analytic_hr_department_restriction/models/account_analytic_plan.py
  analytic_hr_department_restriction/models/ir_rule.py
  analytic_hr_department_restriction/pyproject.toml
  analytic_hr_department_restriction/readme/CONFIGURE.md
  analytic_hr_department_restriction/readme/CONTRIBUTORS.md
  analytic_hr_department_restriction/readme/DESCRIPTION.md
  analytic_hr_department_restriction/readme/USAGE.md
  analytic_hr_department_restriction/security/groups.xml
  analytic_hr_department_restriction/static/description/icon.png
  analytic_hr_department_restriction/static/description/index.html
  analytic_hr_department_restriction/tests/__init__.py
  analytic_hr_department_restriction/tests/test_analytic_hr_department_restriction.py
  analytic_hr_department_restriction/views/account_analytic_account_views.xml
  analytic_hr_department_restriction/views/account_analytic_plan_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#787 [16.0][TMP] account_analytic_distribution_manual: Temporarily disable test …
  account_analytic_distribution_manual/tests/test_analytic_distribution_manual_tour.py
Labels: bot is merging ⏳

#785 [16.0][FIX] account_analytic_distribution_manual: fix crash in post install script
  account_analytic_distribution_manual/hooks.py
Labels: bot is merging ⏳

#786 [16.0][FIX] product_analytic: Use record and not recordset in compute method + remove `depends_context`
  product_analytic/models/account_move_line.py
Labels: enhancement, needs review, approved, bot is merging ⏳
